using System;
using System.Runtime.InteropServices;

namespace IceFlake.Client.Patchables
{

    #region Game related

    public enum GlueScreen
    {
        Unknown = -1,
        Login,
        PatchDownload,
        CharSelect,
        CharCreate,
        TrialConvert,
        Movie,
        RealmList,
        Credits,
        RealmWizard,
        End
    }

    public enum GameState
    {
        Idling,
        LoggingIn,
        ChangingRealm,
        SelectingCharacter,
        QueryingRealmList,
        CreatingCharacter,
        DeletingCharacter,
        ChracterRename,
        CharacterDecline,
        ChangingFactionOrRace,
        Zoning,
        Exiting,
        NonPersonalInfoSurvey,
        Unknown,
        ScanDllScanning
    }

    public enum GameError
    {
        ERR_INV_FULL = 0x0,
        ERR_BANK_FULL = 0x1,
        ERR_CANT_EQUIP_LEVEL_I = 0x2,
        ERR_CANT_EQUIP_SKILL = 0x3,
        ERR_CANT_EQUIP_EVER = 0x4,
        ERR_CANT_EQUIP_RANK = 0x5,
        ERR_CANT_EQUIP_RATING = 0x6,
        ERR_CANT_EQUIP_REPUTATION = 0x7,
        ERR_PROFICIENCY_NEEDED = 0x8,
        ERR_WRONG_SLOT = 0x9,
        ERR_CANT_EQUIP_NEED_TALENT = 0x0A,
        ERR_BAG_FULL = 0x0B,
        ERR_INTERNAL_BAG_ERROR = 0x0C,
        ERR_DESTROY_NONEMPTY_BAG = 0x0D,
        ERR_BAG_IN_BAG = 0x0E,
        ERR_TOO_MANY_SPECIAL_BAGS = 0x0F,
        ERR_TRADE_EQUIPPED_BAG = 0x10,
        ERR_AMMO_ONLY = 0x11,
        ERR_NO_SLOT_AVAILABLE = 0x12,
        ERR_WRONG_BAG_TYPE = 0x13,
        ERR_ITEM_MAX_COUNT = 0x14,
        ERR_NOT_EQUIPPABLE = 0x15,
        ERR_CANT_STACK = 0x16,
        ERR_CANT_SWAP = 0x17,
        ERR_SLOT_EMPTY = 0x18,
        ERR_ITEM_NOT_FOUND = 0x19,
        ERR_TOO_FEW_TO_SPLIT = 0x1A,
        ERR_SPLIT_FAILED = 0x1B,
        ERR_NOT_A_BAG = 0x1C,
        ERR_NOT_OWNER = 0x1D,
        ERR_ONLY_ONE_QUIVER = 0x1E,
        ERR_NO_BANK_SLOT = 0x1F,
        ERR_NO_BANK_HERE = 0x20,
        ERR_ITEM_LOCKED = 0x21,
        ERR_2HANDED_EQUIPPED = 0x22,
        ERR_VENDOR_NOT_INTERESTED = 0x23,
        ERR_VENDOR_HATES_YOU = 0x24,
        ERR_VENDOR_SOLD_OUT = 0x25,
        ERR_VENDOR_TOO_FAR = 0x26,
        ERR_VENDOR_DOESNT_BUY = 0x27,
        ERR_NOT_ENOUGH_MONEY = 0x28,
        ERR_RECEIVE_ITEM_S = 0x29,
        ERR_DROP_BOUND_ITEM = 0x2A,
        ERR_TRADE_BOUND_ITEM = 0x2B,
        ERR_TRADE_QUEST_ITEM = 0x2C,
        ERR_TRADE_TEMP_ENCHANT_BOUND = 0x2D,
        ERR_TRADE_GROUND_ITEM = 0x2E,
        ERR_TRADE_BAG = 0x2F,
        ERR_SPELL_FAILED_S = 0x30,
        ERR_ITEM_COOLDOWN = 0x31,
        ERR_POTION_COOLDOWN = 0x32,
        ERR_FOOD_COOLDOWN = 0x33,
        ERR_SPELL_COOLDOWN = 0x34,
        ERR_ABILITY_COOLDOWN = 0x35,
        ERR_SPELL_ALREADY_KNOWN_S = 0x36,
        ERR_PET_SPELL_ALREADY_KNOWN_S = 0x37,
        ERR_PROFICIENCY_GAINED_S = 0x38,
        ERR_SKILL_GAINED_S = 0x39,
        ERR_SKILL_UP_SI = 0x3A,
        ERR_LEARN_SPELL_S = 0x3B,
        ERR_LEARN_ABILITY_S = 0x3C,
        ERR_LEARN_RECIPE_S = 0x3D,
        ERR_LEARN_COMPANION_S = 0x3E,
        ERR_INVITE_PLAYER_S = 0x3F,
        ERR_INVITE_SELF = 0x40,
        ERR_INVITED_TO_GROUP_SS = 0x41,
        ERR_INVITED_ALREADY_IN_GROUP_SS = 0x42,
        ERR_ALREADY_IN_GROUP_S = 0x43,
        ERR_PLAYER_BUSY_S = 0x44,
        ERR_NEW_LEADER_S = 0x45,
        ERR_NEW_LEADER_YOU = 0x46,
        ERR_NEW_GUIDE_S = 0x47,
        ERR_NEW_GUIDE_YOU = 0x48,
        ERR_LEFT_GROUP_S = 0x49,
        ERR_LEFT_GROUP_YOU = 0x4A,
        ERR_GROUP_DISBANDED = 0x4B,
        ERR_DECLINE_GROUP_S = 0x4C,
        ERR_JOINED_GROUP_S = 0x4D,
        ERR_UNINVITE_YOU = 0x4E,
        ERR_BAD_PLAYER_NAME_S = 0x4F,
        ERR_NOT_IN_GROUP = 0x50,
        ERR_TARGET_NOT_IN_GROUP_S = 0x51,
        ERR_TARGET_NOT_IN_INSTANCE_S = 0x52,
        ERR_GROUP_FULL = 0x53,
        ERR_NOT_LEADER = 0x54,
        ERR_PLAYER_DIED_S = 0x55,
        ERR_GUILD_CREATE_S = 0x56,
        ERR_GUILD_INVITE_S = 0x57,
        ERR_INVITED_TO_GUILD_SSS = 0x58,
        ERR_ALREADY_IN_GUILD_S = 0x59,
        ERR_ALREADY_INVITED_TO_GUILD_S = 0x5A,
        ERR_INVITED_TO_GUILD = 0x5B,
        ERR_ALREADY_IN_GUILD = 0x5C,
        ERR_GUILD_ACCEPT = 0x5D,
        ERR_GUILD_DECLINE_S = 0x5E,
        ERR_GUILD_PERMISSIONS = 0x5F,
        ERR_GUILD_JOIN_S = 0x60,
        ERR_GUILD_FOUNDER_S = 0x61,
        ERR_GUILD_PROMOTE_SSS = 0x62,
        ERR_GUILD_DEMOTE_SSS = 0x63,
        ERR_GUILD_QUIT_S = 0x64,
        ERR_GUILD_LEAVE_S = 0x65,
        ERR_GUILD_REMOVE_SS = 0x66,
        ERR_GUILD_REMOVE_SELF = 0x67,
        ERR_GUILD_DISBAND_S = 0x68,
        ERR_GUILD_DISBAND_SELF = 0x69,
        ERR_GUILD_LEADER_S = 0x6A,
        ERR_GUILD_LEADER_SELF = 0x6B,
        ERR_GUILD_PLAYER_NOT_FOUND_S = 0x6C,
        ERR_GUILD_PLAYER_NOT_IN_GUILD_S = 0x6D,
        ERR_GUILD_PLAYER_NOT_IN_GUILD = 0x6E,
        ERR_GUILD_CANT_PROMOTE_S = 0x6F,
        ERR_GUILD_CANT_DEMOTE_S = 0x70,
        ERR_GUILD_NOT_IN_A_GUILD = 0x71,
        ERR_GUILD_INTERNAL = 0x72,
        ERR_GUILD_LEADER_IS_S = 0x73,
        ERR_GUILD_LEADER_CHANGED_SS = 0x74,
        ERR_GUILD_DISBANDED = 0x75,
        ERR_GUILD_NOT_ALLIED = 0x76,
        ERR_GUILD_LEADER_LEAVE = 0x77,
        ERR_GUILD_RANKS_LOCKED = 0x78,
        ERR_GUILD_RANK_IN_USE = 0x79,
        ERR_GUILD_RANK_TOO_HIGH_S = 0x7A,
        ERR_GUILD_RANK_TOO_LOW_S = 0x7B,
        ERR_GUILD_NAME_EXISTS_S = 0x7C,
        ERR_GUILD_WITHDRAW_LIMIT = 0x7D,
        ERR_GUILD_NOT_ENOUGH_MONEY = 0x7E,
        ERR_GUILD_BANK_CONJURED_ITEM = 0x7F,
        ERR_GUILD_BANK_EQUIPPED_ITEM = 0x80,
        ERR_GUILD_BANK_BOUND_ITEM = 0x81,
        ERR_GUILD_BANK_QUEST_ITEM = 0x82,
        ERR_GUILD_BANK_WRAPPED_ITEM = 0x83,
        ERR_GUILD_BANK_FULL = 0x84,
        ERR_NO_GUILD_CHARTER = 0x85,
        ERR_OUT_OF_RANGE = 0x86,
        ERR_PLAYER_DEAD = 0x87,
        ERR_CLIENT_LOCKED_OUT = 0x88,
        ERR_KILLED_BY_S = 0x89,
        ERR_LOOT_LOCKED = 0x8A,
        ERR_LOOT_TOO_FAR = 0x8B,
        ERR_LOOT_DIDNT_KILL = 0x8C,
        ERR_LOOT_BAD_FACING = 0x8D,
        ERR_LOOT_NOTSTANDING = 0x8E,
        ERR_LOOT_STUNNED = 0x8F,
        ERR_LOOT_NO_UI = 0x90,
        ERR_LOOT_WHILE_INVULNERABLE = 0x91,
        ERR_QUEST_ACCEPTED_S = 0x92,
        ERR_QUEST_COMPLETE_S = 0x93,
        ERR_QUEST_FAILED_S = 0x94,
        ERR_QUEST_FAILED_BAG_FULL_S = 0x95,
        ERR_QUEST_FAILED_MAX_COUNT_S = 0x96,
        ERR_QUEST_FAILED_LOW_LEVEL = 0x97,
        ERR_QUEST_FAILED_MISSING_ITEMS = 0x98,
        ERR_QUEST_FAILED_WRONG_RACE = 0x99,
        ERR_QUEST_FAILED_NOT_ENOUGH_MONEY = 0x9A,
        ERR_QUEST_FAILED_EXPANSION = 0x9B,
        ERR_QUEST_ONLY_ONE_TIMED = 0x9C,
        ERR_QUEST_NEED_PREREQS = 0x9D,
        ERR_QUEST_ALREADY_ON = 0x9E,
        ERR_QUEST_ALREADY_DONE = 0x9F,
        ERR_QUEST_ALREADY_DONE_DAILY = 0x0A0,
        ERR_QUEST_REWARD_EXP_I = 0x0A1,
        ERR_QUEST_REWARD_ITEM_S = 0x0A2,
        ERR_QUEST_REWARD_ITEM_MULT_IS = 0x0A3,
        ERR_QUEST_REWARD_MONEY_S = 0x0A4,
        ERR_QUEST_MUST_CHOOSE = 0x0A5,
        ERR_QUEST_LOG_FULL = 0x0A6,
        ERR_COMBAT_DAMAGE_SSI = 0x0A7,
        ERR_INSPECT_S = 0x0A8,
        ERR_CANT_USE_ITEM = 0x0A9,
        ERR_CANT_USE_ITEM_IN_ARENA = 0x0AA,
        ERR_MUST_EQUIP_ITEM = 0x0AB,
        ERR_PASSIVE_ABILITY = 0x0AC,
        ERR_2HSKILLNOTFOUND = 0x0AD,
        ERR_NO_ATTACK_TARGET = 0x0AE,
        ERR_INVALID_ATTACK_TARGET = 0x0AF,
        ERR_ATTACK_STUNNED = 0x0B0,
        ERR_ATTACK_PACIFIED = 0x0B1,
        ERR_ATTACK_MOUNTED = 0x0B2,
        ERR_ATTACK_FLEEING = 0x0B3,
        ERR_ATTACK_CONFUSED = 0x0B4,
        ERR_ATTACK_CHARMED = 0x0B5,
        ERR_ATTACK_DEAD = 0x0B6,
        ERR_ATTACK_PREVENTED_BY_MECHANIC_S = 0x0B7,
        ERR_ATTACK_CHANNEL = 0x0B8,
        ERR_TAXISAMENODE = 0x0B9,
        ERR_TAXINOSUCHPATH = 0x0BA,
        ERR_TAXIUNSPECIFIEDSERVERERROR = 0x0BB,
        ERR_TAXINOTENOUGHMONEY = 0x0BC,
        ERR_TAXITOOFARAWAY = 0x0BD,
        ERR_TAXINOVENDORNEARBY = 0x0BE,
        ERR_TAXINOTVISITED = 0x0BF,
        ERR_TAXIPLAYERBUSY = 0x0C0,
        ERR_TAXIPLAYERALREADYMOUNTED = 0x0C1,
        ERR_TAXIPLAYERSHAPESHIFTED = 0x0C2,
        ERR_TAXIPLAYERMOVING = 0x0C3,
        ERR_TAXINOPATHS = 0x0C4,
        ERR_TAXINOTSTANDING = 0x0C5,
        ERR_NO_REPLY_TARGET = 0x0C6,
        ERR_GENERIC_NO_TARGET = 0x0C7,
        ERR_INITIATE_TRADE_S = 0x0C8,
        ERR_TRADE_REQUEST_S = 0x0C9,
        ERR_TRADE_BLOCKED_S = 0x0CA,
        ERR_TRADE_TARGET_DEAD = 0x0CB,
        ERR_TRADE_TOO_FAR = 0x0CC,
        ERR_TRADE_CANCELLED = 0x0CD,
        ERR_TRADE_COMPLETE = 0x0CE,
        ERR_TRADE_BAG_FULL = 0x0CF,
        ERR_TRADE_TARGET_BAG_FULL = 0x0D0,
        ERR_TRADE_MAX_COUNT_EXCEEDED = 0x0D1,
        ERR_TRADE_TARGET_MAX_COUNT_EXCEEDED = 0x0D2,
        ERR_ALREADY_TRADING = 0x0D3,
        ERR_MOUNT_INVALIDMOUNTEE = 0x0D4,
        ERR_MOUNT_TOOFARAWAY = 0x0D5,
        ERR_MOUNT_ALREADYMOUNTED = 0x0D6,
        ERR_MOUNT_NOTMOUNTABLE = 0x0D7,
        ERR_MOUNT_NOTYOURPET = 0x0D8,
        ERR_MOUNT_OTHER = 0x0D9,
        ERR_MOUNT_LOOTING = 0x0DA,
        ERR_MOUNT_RACECANTMOUNT = 0x0DB,
        ERR_MOUNT_SHAPESHIFTED = 0x0DC,
        ERR_DISMOUNT_NOPET = 0x0DD,
        ERR_DISMOUNT_NOTMOUNTED = 0x0DE,
        ERR_DISMOUNT_NOTYOURPET = 0x0DF,
        ERR_SPELL_FAILED_TOTEMS = 0x0E0,
        ERR_SPELL_FAILED_REAGENTS = 0x0E1,
        ERR_SPELL_FAILED_REAGENTS_GENERIC = 0x0E2,
        ERR_SPELL_FAILED_EQUIPPED_ITEM = 0x0E3,
        ERR_SPELL_FAILED_EQUIPPED_ITEM_CLASS_S = 0x0E4,
        ERR_SPELL_FAILED_SHAPESHIFT_FORM_S = 0x0E5,
        ERR_BADATTACKFACING = 0x0E6,
        ERR_BADATTACKPOS = 0x0E7,
        ERR_CHEST_IN_USE = 0x0E8,
        ERR_USE_CANT_OPEN = 0x0E9,
        ERR_USE_LOCKED = 0x0EA,
        ERR_DOOR_LOCKED = 0x0EB,
        ERR_BUTTON_LOCKED = 0x0EC,
        ERR_USE_LOCKED_WITH_ITEM_S = 0x0ED,
        ERR_USE_LOCKED_WITH_SPELL_S = 0x0EE,
        ERR_USE_LOCKED_WITH_SPELL_KNOWN_SI = 0x0EF,
        ERR_USE_TOO_FAR = 0x0F0,
        ERR_USE_BAD_ANGLE = 0x0F1,
        ERR_USE_OBJECT_MOVING = 0x0F2,
        ERR_USE_SPELL_FOCUS = 0x0F3,
        ERR_USE_DESTROYED = 0x0F4,
        ERR_SET_LOOT_FREEFORALL = 0x0F5,
        ERR_SET_LOOT_ROUNDROBIN = 0x0F6,
        ERR_SET_LOOT_MASTER = 0x0F7,
        ERR_SET_LOOT_GROUP = 0x0F8,
        ERR_SET_LOOT_NBG = 0x0F9,
        ERR_SET_LOOT_THRESHOLD_S = 0x0FA,
        ERR_NEW_LOOT_MASTER_S = 0x0FB,
        ERR_SPECIFY_MASTER_LOOTER = 0x0FC,
        ERR_TAME_FAILED = 0x0FD,
        ERR_CHAT_WHILE_DEAD = 0x0FE,
        ERR_CHAT_WRONG_FACTION = 0x0FF,
        ERR_CHAT_PLAYER_NOT_FOUND_S = 0x100,
        ERR_NEWTAXIPATH = 0x101,
        ERR_NO_PET = 0x102,
        ERR_NOTYOURPET = 0x103,
        ERR_PET_NOT_RENAMEABLE = 0x104,
        ERR_QUEST_OBJECTIVE_COMPLETE_S = 0x105,
        ERR_QUEST_UNKNOWN_COMPLETE = 0x106,
        ERR_QUEST_ADD_KILL_SII = 0x107,
        ERR_QUEST_ADD_FOUND_SII = 0x108,
        ERR_QUEST_ADD_ITEM_SII = 0x109,
        ERR_QUEST_ADD_PLAYER_KILL_SII = 0x10A,
        ERR_CANNOTCREATEDIRECTORY = 0x10B,
        ERR_CANNOTCREATEFILE = 0x10C,
        ERR_PLAYER_WRONG_FACTION = 0x10D,
        ERR_BANKSLOT_FAILED_TOO_MANY = 0x10E,
        ERR_BANKSLOT_INSUFFICIENT_FUNDS = 0x10F,
        ERR_BANKSLOT_NOTBANKER = 0x110,
        ERR_FRIEND_DB_ERROR = 0x111,
        ERR_FRIEND_LIST_FULL = 0x112,
        ERR_FRIEND_ADDED_S = 0x113,
        ERR_FRIEND_ONLINE_SS = 0x114,
        ERR_FRIEND_OFFLINE_S = 0x115,
        ERR_FRIEND_NOT_FOUND = 0x116,
        ERR_FRIEND_WRONG_FACTION = 0x117,
        ERR_FRIEND_REMOVED_S = 0x118,
        ERR_FRIEND_ERROR = 0x119,
        ERR_FRIEND_ALREADY_S = 0x11A,
        ERR_FRIEND_SELF = 0x11B,
        ERR_FRIEND_DELETED = 0x11C,
        ERR_IGNORE_FULL = 0x11D,
        ERR_IGNORE_SELF = 0x11E,
        ERR_IGNORE_NOT_FOUND = 0x11F,
        ERR_IGNORE_ALREADY_S = 0x120,
        ERR_IGNORE_ADDED_S = 0x121,
        ERR_IGNORE_REMOVED_S = 0x122,
        ERR_IGNORE_AMBIGUOUS = 0x123,
        ERR_IGNORE_DELETED = 0x124,
        ERR_ONLY_ONE_BOLT = 0x125,
        ERR_ONLY_ONE_AMMO = 0x126,
        ERR_SPELL_FAILED_EQUIPPED_SPECIFIC_ITEM = 0x127,
        ERR_WRONG_BAG_TYPE_SUBCLASS = 0x128,
        ERR_CANT_WRAP_STACKABLE = 0x129,
        ERR_CANT_WRAP_EQUIPPED = 0x12A,
        ERR_CANT_WRAP_WRAPPED = 0x12B,
        ERR_CANT_WRAP_BOUND = 0x12C,
        ERR_CANT_WRAP_UNIQUE = 0x12D,
        ERR_CANT_WRAP_BAGS = 0x12E,
        ERR_OUT_OF_MANA = 0x12F,
        ERR_OUT_OF_RAGE = 0x130,
        ERR_OUT_OF_FOCUS = 0x131,
        ERR_OUT_OF_ENERGY = 0x132,
        ERR_OUT_OF_HEALTH = 0x133,
        ERR_OUT_OF_RUNES = 0x134,
        ERR_OUT_OF_RUNIC_POWER = 0x135,
        ERR_OUT_OF_POWER_DISPLAY = 0x136,
        ERR_LOOT_GONE = 0x137,
        ERR_MOUNT_FORCEDDISMOUNT = 0x138,
        ERR_AUTOFOLLOW_TOO_FAR = 0x139,
        ERR_UNIT_NOT_FOUND = 0x13A,
        ERR_INVALID_FOLLOW_TARGET = 0x13B,
        ERR_INVALID_INSPECT_TARGET = 0x13C,
        ERR_GUILDEMBLEM_SUCCESS = 0x13D,
        ERR_GUILDEMBLEM_INVALID_TABARD_COLORS = 0x13E,
        ERR_GUILDEMBLEM_NOGUILD = 0x13F,
        ERR_GUILDEMBLEM_NOTGUILDMASTER = 0x140,
        ERR_GUILDEMBLEM_NOTENOUGHMONEY = 0x141,
        ERR_GUILDEMBLEM_INVALIDVENDOR = 0x142,
        ERR_EMBLEMERROR_NOTABARDGEOSET = 0x143,
        ERR_SPELL_OUT_OF_RANGE = 0x144,
        ERR_COMMAND_NEEDS_TARGET = 0x145,
        ERR_NOAMMO_S = 0x146,
        ERR_TOOBUSYTOFOLLOW = 0x147,
        ERR_DUEL_REQUESTED = 0x148,
        ERR_DUEL_CANCELLED = 0x149,
        ERR_DEATHBINDALREADYBOUND = 0x14A,
        ERR_DEATHBIND_SUCCESS_S = 0x14B,
        ERR_NOEMOTEWHILERUNNING = 0x14C,
        ERR_ZONE_EXPLORED = 0x14D,
        ERR_ZONE_EXPLORED_XP = 0x14E,
        ERR_INVALID_ITEM_TARGET = 0x14F,
        ERR_IGNORING_YOU_S = 0x150,
        ERR_FISH_NOT_HOOKED = 0x151,
        ERR_FISH_ESCAPED = 0x152,
        ERR_SPELL_FAILED_NOTUNSHEATHED = 0x153,
        ERR_PETITION_OFFERED_S = 0x154,
        ERR_PETITION_SIGNED = 0x155,
        ERR_PETITION_SIGNED_S = 0x156,
        ERR_PETITION_DECLINED_S = 0x157,
        ERR_PETITION_ALREADY_SIGNED = 0x158,
        ERR_PETITION_RESTRICTED_ACCOUNT = 0x159,
        ERR_PETITION_ALREADY_SIGNED_OTHER = 0x15A,
        ERR_PETITION_IN_GUILD = 0x15B,
        ERR_PETITION_CREATOR = 0x15C,
        ERR_PETITION_NOT_ENOUGH_SIGNATURES = 0x15D,
        ERR_PETITION_NOT_SAME_SERVER = 0x15E,
        ERR_PETITION_FULL = 0x15F,
        ERR_SPELL_UNLEARNED_S = 0x160,
        ERR_PET_SPELL_ROOTED = 0x161,
        ERR_PET_SPELL_AFFECTING_COMBAT = 0x162,
        ERR_PET_SPELL_OUT_OF_RANGE = 0x163,
        ERR_PET_SPELL_NOT_BEHIND = 0x164,
        ERR_PET_SPELL_TARGETS_DEAD = 0x165,
        ERR_PET_SPELL_DEAD = 0x166,
        ERR_PET_SPELL_NOPATH = 0x167,
        ERR_ITEM_CANT_BE_DESTROYED = 0x168,
        ERR_TICKET_ALREADY_EXISTS = 0x169,
        ERR_TICKET_CREATE_ERROR = 0x16A,
        ERR_TICKET_UPDATE_ERROR = 0x16B,
        ERR_TICKET_DB_ERROR = 0x16C,
        ERR_TICKET_NO_TEXT = 0x16D,
        ERR_TICKET_TEXT_TOO_LONG = 0x16E,
        ERR_OBJECT_IS_BUSY = 0x16F,
        ERR_EXHAUSTION_WELLRESTED = 0x170,
        ERR_EXHAUSTION_RESTED = 0x171,
        ERR_EXHAUSTION_NORMAL = 0x172,
        ERR_EXHAUSTION_TIRED = 0x173,
        ERR_EXHAUSTION_EXHAUSTED = 0x174,
        ERR_NO_ITEMS_WHILE_SHAPESHIFTED = 0x175,
        ERR_CANT_INTERACT_SHAPESHIFTED = 0x176,
        ERR_MAIL_QUEST_ITEM = 0x177,
        ERR_MAIL_BOUND_ITEM = 0x178,
        ERR_MAIL_CONJURED_ITEM = 0x179,
        ERR_MAIL_BAG = 0x17A,
        ERR_MAIL_TO_SELF = 0x17B,
        ERR_MAIL_TARGET_NOT_FOUND = 0x17C,
        ERR_MAIL_DATABASE_ERROR = 0x17D,
        ERR_MAIL_WRAPPED_COD = 0x17E,
        ERR_MAIL_SENT = 0x17F,
        ERR_NOT_HAPPY_ENOUGH = 0x180,
        ERR_USE_CANT_IMMUNE = 0x181,
        ERR_CANT_BE_DISENCHANTED = 0x182,
        ERR_CANT_USE_DISARMED = 0x183,
        ERR_AUCTION_QUEST_ITEM = 0x184,
        ERR_AUCTION_BOUND_ITEM = 0x185,
        ERR_AUCTION_CONJURED_ITEM = 0x186,
        ERR_AUCTION_LIMITED_DURATION_ITEM = 0x187,
        ERR_AUCTION_WRAPPED_ITEM = 0x188,
        ERR_AUCTION_LOOT_ITEM = 0x189,
        ERR_AUCTION_BAG = 0x18A,
        ERR_AUCTION_DATABASE_ERROR = 0x18B,
        ERR_AUCTION_BID_OWN = 0x18C,
        ERR_AUCTION_BID_INCREMENT = 0x18D,
        ERR_AUCTION_HIGHER_BID = 0x18E,
        ERR_AUCTION_MIN_BID = 0x18F,
        ERR_AUCTION_REPAIR_ITEM = 0x190,
        ERR_AUCTION_USED_CHARGES = 0x191,
        ERR_AUCTION_STARTED = 0x192,
        ERR_AUCTION_REMOVED = 0x193,
        ERR_AUCTION_OUTBID_S = 0x194,
        ERR_AUCTION_WON_S = 0x195,
        ERR_AUCTION_SOLD_S = 0x196,
        ERR_AUCTION_EXPIRED_S = 0x197,
        ERR_AUCTION_REMOVED_S = 0x198,
        ERR_AUCTION_BID_PLACED = 0x199,
        ERR_LOGOUT_FAILED = 0x19A,
        ERR_QUEST_PUSH_SUCCESS_S = 0x19B,
        ERR_QUEST_PUSH_INVALID_S = 0x19C,
        ERR_QUEST_PUSH_ACCEPTED_S = 0x19D,
        ERR_QUEST_PUSH_DECLINED_S = 0x19E,
        ERR_QUEST_PUSH_BUSY_S = 0x19F,
        ERR_QUEST_PUSH_LOG_FULL_S = 0x1A0,
        ERR_QUEST_PUSH_ONQUEST_S = 0x1A1,
        ERR_QUEST_PUSH_ALREADY_DONE_S = 0x1A2,
        ERR_QUEST_PUSH_NOT_DAILY_S = 0x1A3,
        ERR_QUEST_PUSH_TIMER_EXPIRED_S = 0x1A4,
        ERR_QUEST_PUSH_NOT_IN_PARTY_S = 0x1A5,
        ERR_QUEST_PUSH_DIFFERENT_SERVER_DAILY_S = 0x1A6,
        ERR_RAID_GROUP_LOWLEVEL = 0x1A7,
        ERR_RAID_GROUP_ONLY = 0x1A8,
        ERR_RAID_GROUP_FULL = 0x1A9,
        ERR_RAID_GROUP_REQUIREMENTS_UNMATCH = 0x1AA,
        ERR_CORPSE_IS_NOT_IN_INSTANCE = 0x1AB,
        ERR_PVP_KILL_HONORABLE = 0x1AC,
        ERR_PVP_KILL_DISHONORABLE = 0x1AD,
        ERR_SPELL_FAILED_ALREADY_AT_FULL_HEALTH = 0x1AE,
        ERR_SPELL_FAILED_ALREADY_AT_FULL_MANA = 0x1AF,
        ERR_SPELL_FAILED_ALREADY_AT_FULL_POWER_S = 0x1B0,
        ERR_AUTOLOOT_MONEY_S = 0x1B1,
        ERR_GENERIC_STUNNED = 0x1B2,
        ERR_TARGET_STUNNED = 0x1B3,
        ERR_MUST_REPAIR_DURABILITY = 0x1B4,
        ERR_RAID_YOU_JOINED = 0x1B5,
        ERR_RAID_YOU_LEFT = 0x1B6,
        ERR_RAID_MEMBER_ADDED_S = 0x1B7,
        ERR_RAID_MEMBER_REMOVED_S = 0x1B8,
        ERR_CLICK_ON_ITEM_TO_FEED = 0x1B9,
        ERR_TOO_MANY_CHAT_CHANNELS = 0x1BA,
        ERR_LOOT_ROLL_PENDING = 0x1BB,
        ERR_LOOT_PLAYER_NOT_FOUND = 0x1BC,
        ERR_NOT_IN_RAID = 0x1BD,
        ERR_LOGGING_OUT = 0x1BE,
        ERR_TARGET_LOGGING_OUT = 0x1BF,
        ERR_NOT_WHILE_MOUNTED = 0x1C0,
        ERR_NOT_WHILE_SHAPESHIFTED = 0x1C1,
        ERR_NOT_IN_COMBAT = 0x1C2,
        ERR_NOT_WHILE_DISARMED = 0x1C3,
        ERR_PET_BROKEN = 0x1C4,
        ERR_TALENT_WIPE_ERROR = 0x1C5,
        ERR_FEIGN_DEATH_RESISTED = 0x1C6,
        ERR_MEETING_STONE_IN_QUEUE_S = 0x1C7,
        ERR_MEETING_STONE_LEFT_QUEUE_S = 0x1C8,
        ERR_MEETING_STONE_OTHER_MEMBER_LEFT = 0x1C9,
        ERR_MEETING_STONE_PARTY_KICKED_FROM_QUEUE = 0x1CA,
        ERR_MEETING_STONE_MEMBER_STILL_IN_QUEUE = 0x1CB,
        ERR_MEETING_STONE_SUCCESS = 0x1CC,
        ERR_MEETING_STONE_IN_PROGRESS = 0x1CD,
        ERR_MEETING_STONE_MEMBER_ADDED_S = 0x1CE,
        ERR_MEETING_STONE_GROUP_FULL = 0x1CF,
        ERR_MEETING_STONE_NOT_LEADER = 0x1D0,
        ERR_MEETING_STONE_INVALID_LEVEL = 0x1D1,
        ERR_MEETING_STONE_TARGET_NOT_IN_PARTY = 0x1D2,
        ERR_MEETING_STONE_TARGET_INVALID_LEVEL = 0x1D3,
        ERR_MEETING_STONE_MUST_BE_LEADER = 0x1D4,
        ERR_MEETING_STONE_NO_RAID_GROUP = 0x1D5,
        ERR_MEETING_STONE_NEED_PARTY = 0x1D6,
        ERR_MEETING_STONE_NOT_FOUND = 0x1D7,
        ERR_GUILDEMBLEM_SAME = 0x1D8,
        ERR_EQUIP_TRADE_ITEM = 0x1D9,
        ERR_PVP_TOGGLE_ON = 0x1DA,
        ERR_PVP_TOGGLE_OFF = 0x1DB,
        ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS = 0x1DC,
        ERR_GROUP_JOIN_BATTLEGROUND_S = 0x1DD,
        ERR_GROUP_JOIN_BATTLEGROUND_FAIL = 0x1DE,
        ERR_GROUP_JOIN_BATTLEGROUND_TOO_MANY = 0x1DF,
        ERR_BATTLEGROUND_TOO_MANY_QUEUES = 0x1E0,
        ERR_BATTLEGROUND_CANNOT_QUEUE_FOR_RATED = 0x1E1,
        ERR_BATTLEDGROUND_QUEUED_FOR_RATED = 0x1E2,
        ERR_BATTLEGROUND_TEAM_LEFT_QUEUE = 0x1E3,
        ERR_BATTLEGROUND_NOT_IN_BATTLEGROUND = 0x1E4,
        ERR_INVALID_PROMOTION_CODE = 0x1E5,
        ERR_BG_PLAYER_JOINED_SS = 0x1E6,
        ERR_BG_PLAYER_LEFT_S = 0x1E7,
        ERR_RESTRICTED_ACCOUNT = 0x1E8,
        ERR_PLAY_TIME_EXCEEDED = 0x1E9,
        ERR_APPROACHING_PARTIAL_PLAY_TIME = 0x1EA,
        ERR_APPROACHING_PARTIAL_PLAY_TIME_2 = 0x1EB,
        ERR_APPROACHING_NO_PLAY_TIME = 0x1EC,
        ERR_APPROACHING_NO_PLAY_TIME_2 = 0x1ED,
        ERR_UNHEALTHY_TIME = 0x1EE,
        ERR_CHAT_RESTRICTED = 0x1EF,
        ERR_CHAT_THROTTLED = 0x1F0,
        ERR_MAIL_REACHED_CAP = 0x1F1,
        ERR_INVALID_RAID_TARGET = 0x1F2,
        ERR_RAID_LEADER_READY_CHECK_START_S = 0x1F3,
        ERR_READY_CHECK_IN_PROGRESS = 0x1F4,
        ERR_READY_CHECK_THROTTLED = 0x1F5,
        ERR_DUNGEON_DIFFICULTY_FAILED = 0x1F6,
        ERR_DUNGEON_DIFFICULTY_CHANGED_S = 0x1F7,
        ERR_TRADE_WRONG_REALM = 0x1F8,
        ERR_TRADE_NOT_ON_TAPLIST = 0x1F9,
        ERR_CHAT_PLAYER_AMBIGUOUS_S = 0x1FA,
        ERR_LOOT_CANT_LOOT_THAT_NOW = 0x1FB,
        ERR_LOOT_MASTER_INV_FULL = 0x1FC,
        ERR_LOOT_MASTER_UNIQUE_ITEM = 0x1FD,
        ERR_LOOT_MASTER_OTHER = 0x1FE,
        ERR_FILTERING_YOU_S = 0x1FF,
        ERR_USE_PREVENTED_BY_MECHANIC_S = 0x200,
        ERR_ITEM_UNIQUE_EQUIPPABLE = 0x201,
        ERR_LFG_LEADER_IS_LFM_S = 0x202,
        ERR_LFG_PENDING = 0x203,
        ERR_ARENA_NO_TEAM_II = 0x204,
        ERR_ARENA_TEAM_CREATE_S = 0x205,
        ERR_ARENA_TEAM_INVITE_SS = 0x206,
        ERR_ARENA_TEAM_QUIT_S = 0x207,
        ERR_ARENA_TEAM_FOUNDER_S = 0x208,
        ERR_ARENA_TEAM_INTERNAL = 0x209,
        ERR_ALREADY_IN_ARENA_TEAM = 0x20A,
        ERR_ALREADY_IN_ARENA_TEAM_S = 0x20B,
        ERR_INVITED_TO_ARENA_TEAM = 0x20C,
        ERR_ALREADY_INVITED_TO_ARENA_TEAM_S = 0x20D,
        ERR_ARENA_TEAM_NAME_INVALID = 0x20E,
        ERR_ARENA_TEAM_NAME_EXISTS_S = 0x20F,
        ERR_ARENA_TEAM_LEADER_LEAVE_S = 0x210,
        ERR_ARENA_TEAM_PERMISSIONS = 0x211,
        ERR_ARENA_TEAM_PLAYER_NOT_IN_TEAM = 0x212,
        ERR_ARENA_TEAM_PLAYER_NOT_IN_TEAM_SS = 0x213,
        ERR_ARENA_TEAM_PLAYER_NOT_FOUND_S = 0x214,
        ERR_ARENA_TEAM_NOT_ALLIED = 0x215,
        ERR_ARENA_TEAM_JOIN_SS = 0x216,
        ERR_ARENA_TEAM_YOU_JOIN_S = 0x217,
        ERR_ARENA_TEAM_LEAVE_SS = 0x218,
        ERR_ARENA_TEAM_LEADER_IS_SS = 0x219,
        ERR_ARENA_TEAM_LEADER_CHANGED_SSS = 0x21A,
        ERR_ARENA_TEAM_REMOVE_SSS = 0x21B,
        ERR_ARENA_TEAM_DISBANDED_S = 0x21C,
        ERR_ARENA_TEAM_TARGET_TOO_LOW_S = 0x21D,
        ERR_ARENA_TEAM_TARGET_TOO_HIGH_S = 0x21E,
        ERR_ARENA_TEAM_TOO_MANY_MEMBERS_S = 0x21F,
        ERR_ARENA_TEAM_LEVEL_TOO_LOW_I = 0x220,
        ERR_ARENA_TEAM_NOT_FOUND = 0x221,
        ERR_ARENA_TEAMS_LOCKED = 0x222,
        ERR_NO_ARENA_CHARTER = 0x223,
        ERR_CANT_SPEAK_LANGAGE = 0x224,
        ERR_VENDOR_MISSING_TURNINS = 0x225,
        ERR_BATTLEGROUND_NOT_IN_TEAM = 0x226,
        ERR_NOT_IN_BATTLEGROUND = 0x227,
        ERR_NOT_ENOUGH_HONOR_POINTS = 0x228,
        ERR_NOT_ENOUGH_ARENA_POINTS = 0x229,
        ERR_SOCKETING_REQUIRES_META_GEM = 0x22A,
        ERR_SOCKETING_META_GEM_ONLY_IN_METASLOT = 0x22B,
        ERR_ITEM_MAX_COUNT_SOCKETED = 0x22C,
        ERR_SYSTEM_DISABLED = 0x22D,
        ERR_QUEST_FAILED_TOO_MANY_DAILY_QUESTS_I = 0x22E,
        ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED = 0x22F,
        ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED = 0x230,
        ERR_USER_SQUELCHED = 0x231,
        ERR_TOO_MUCH_GOLD = 0x232,
        ERR_NOT_BARBER_SITTING = 0x233,
        ERR_QUEST_FAILED_CAIS = 0x234,
        ERR_INVITE_RESTRICTED = 0x235,
        ERR_VOICE_IGNORE_FULL = 0x236,
        ERR_VOICE_IGNORE_SELF = 0x237,
        ERR_VOICE_IGNORE_NOT_FOUND = 0x238,
        ERR_VOICE_IGNORE_ALREADY_S = 0x239,
        ERR_VOICE_IGNORE_ADDED_S = 0x23A,
        ERR_VOICE_IGNORE_REMOVED_S = 0x23B,
        ERR_VOICE_IGNORE_AMBIGUOUS = 0x23C,
        ERR_VOICE_IGNORE_DELETED = 0x23D,
        ERR_UNKNOWN_MACRO_OPTION_S = 0x23E,
        ERR_NOT_DURING_ARENA_MATCH = 0x23F,
        ERR_PLAYER_SILENCED = 0x240,
        ERR_PLAYER_UNSILENCED = 0x241,
        ERR_COMSAT_DISCONNECT = 0x242,
        ERR_COMSAT_RECONNECT_ATTEMPT = 0x243,
        ERR_COMSAT_CONNECT_FAIL = 0x244,
        ERR_DANCE_CREATE_DUPLICATE = 0x245,
        ERR_DANCE_SAVE_FAILED = 0x246,
        ERR_DANCE_DELETE_FAILED = 0x247,
        ERR_MAIL_INVALID_ATTACHMENT_SLOT = 0x248,
        ERR_MAIL_TOO_MANY_ATTACHMENTS = 0x249,
        ERR_MAIL_INVALID_ATTACHMENT = 0x24A,
        ERR_MAIL_ATTACHMENT_EXPIRED = 0x24B,
        ERR_VOICE_CHAT_PARENTAL_DISABLE_ALL = 0x24C,
        ERR_VOICE_CHAT_PARENTAL_DISABLE_MIC = 0x24D,
        ERR_PROFANE_CHAT_NAME = 0x24E,
        ERR_PLAYER_SILENCED_ECHO = 0x24F,
        ERR_PLAYER_UNSILENCED_ECHO = 0x250,
        ERR_VOICESESSION_FULL = 0x251,
        ERR_LOOT_CANT_LOOT_THAT = 0x252,
        ERR_ARENA_EXPIRED_CAIS = 0x253,
        ERR_GROUP_ACTION_THROTTLED = 0x254,
        ERR_ALREADY_PICKPOCKETED = 0x255,
        ERR_NAME_INVALID = 0x256,
        ERR_NAME_NO_NAME = 0x257,
        ERR_NAME_TOO_SHORT = 0x258,
        ERR_NAME_TOO_LONG = 0x259,
        ERR_NAME_MIXED_LANGUAGES = 0x25A,
        ERR_NAME_PROFANE = 0x25B,
        ERR_NAME_RESERVED = 0x25C,
        ERR_NAME_THREE_CONSECUTIVE = 0x25D,
        ERR_NAME_INVALID_SPACE = 0x25E,
        ERR_NAME_CONSECUTIVE_SPACES = 0x25F,
        ERR_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS = 0x260,
        ERR_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END = 0x261,
        ERR_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME = 0x262,
        ERR_REFER_A_FRIEND_NOT_REFERRED_BY = 0x263,
        ERR_REFER_A_FRIEND_TARGET_TOO_HIGH = 0x264,
        ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS = 0x265,
        ERR_REFER_A_FRIEND_TOO_FAR = 0x266,
        ERR_REFER_A_FRIEND_DIFFERENT_FACTION = 0x267,
        ERR_REFER_A_FRIEND_NOT_NOW = 0x268,
        ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I = 0x269,
        ERR_REFER_A_FRIEND_SUMMON_LEVEL_MAX_I = 0x26A,
        ERR_REFER_A_FRIEND_SUMMON_COOLDOWN = 0x26B,
        ERR_REFER_A_FRIEND_SUMMON_OFFLINE_S = 0x26C,
        ERR_REFER_A_FRIEND_INSUF_EXPAN_LVL = 0x26D,
        ERR_NOT_SAME_ACCOUNT = 0x26E,
        ERR_BAD_ON_USE_ENCHANT = 0x26F,
        ERR_TRADE_SELF = 0x270,
        ERR_TOO_MANY_SOCKETS = 0x271,
        ERR_ITEM_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED_IS = 0x272,
        ERR_TRADE_TARGET_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED_IS = 0x273,
        ERR_ITEM_MAX_LIMIT_CATEGORY_SOCKETED_EXCEEDED_IS = 0x274,
        ERR_ITEM_MAX_LIMIT_CATEGORY_EQUIPPED_EXCEEDED_IS = 0x275,
        ERR_SHAPESHIFT_FORM_CANNOT_EQUIP = 0x276,
        ERR_ITEM_INVENTORY_FULL_SATCHEL = 0x277,
        ERR_SCALING_STAT_ITEM_LEVEL_EXCEEDED = 0x278,
        ERR_PURCHASE_LEVEL_TOO_LOW = 0x279,
        ERR_GROUP_SWAP_FAILED = 0x27A,
        ERR_INVITE_IN_COMBAT = 0x27B,
        ERR_INVALID_GLYPH_SLOT = 0x27C,
        ERR_GENERIC_NO_VALID_TARGETS = 0x27D,
        ERR_CALENDAR_EVENT_ALERT_S = 0x27E,
        ERR_PET_LEARN_SPELL_S = 0x27F,
        ERR_PET_LEARN_ABILITY_S = 0x280,
        ERR_PET_SPELL_UNLEARNED_S = 0x281,
        ERR_INVITE_UNKNOWN_REALM = 0x282,
        ERR_INVITE_NO_PARTY_SERVER = 0x283,
        ERR_INVITE_PARTY_BUSY = 0x284,
        ERR_PARTY_TARGET_AMBIGUOUS = 0x285,
        ERR_PARTY_LFG_INVITE_RAID_LOCKED = 0x286,
        ERR_PARTY_LFG_BOOT_LIMIT = 0x287,
        ERR_PARTY_LFG_BOOT_COOLDOWN_S = 0x288,
        ERR_PARTY_LFG_BOOT_NOT_ELIGIBLE_S = 0x289,
        ERR_PARTY_LFG_BOOT_IN_PROGRESS = 0x28A,
        ERR_PARTY_LFG_BOOT_TOO_FEW_PLAYERS = 0x28B,
        ERR_PARTY_LFG_BOOT_VOTE_SUCCEEDED = 0x28C,
        ERR_PARTY_LFG_BOOT_VOTE_FAILED = 0x28D,
        ERR_PARTY_LFG_BOOT_IN_COMBAT = 0x28E,
        ERR_PARTY_LFG_BOOT_DUNGEON_COMPLETE = 0x28F,
        ERR_PARTY_LFG_BOOT_LOOT_ROLLS = 0x290,
        ERR_PARTY_LFG_TELEPORT_IN_COMBAT = 0x291,
        ERR_RAID_DISALLOWED_BY_LEVEL = 0x292,
        ERR_BATTLEGROUND_INFO_THROTTLED = 0x293,
        ERR_BATTLEGROUND_ALREADY_IN = 0x294,
        ERR_ARENA_TEAM_CHANGE_FAILED_QUEUED = 0x295,
        ERR_NOT_WHILE_FALLING = 0x296,
        ERR_NOT_WHILE_FATIGUED = 0x297,
        ERR_MAX_SOCKETS = 0x298,
        ERR_MULTI_CAST_ACTION_TOTEM_S = 0x299,
        ERR_REMOVE_FROM_PVP_QUEUE_GRANT_LEVEL = 0x29A,
        ERR_REMOVE_FROM_PVP_QUEUE_XP_GAIN = 0x29B,
        ERR_BATTLEGROUND_JOIN_XP_GAIN = 0x29C,
        ERR_RAID_DIFFICULTY_FAILED = 0x29D,
        ERR_RAID_DIFFICULTY_CHANGED_S = 0x29E,
        ERR_RAID_LOCKOUT_CHANGED_S = 0x29F,
        ERR_PLAYER_DIFFICULTY_CHANGED_S = 0x2A0,
        ERR_GMRESPONSE_DB_ERROR = 0x2A1,
        ERR_BATTLEGROUND_JOIN_RANGE_INDEX = 0x2A2,
        ERR_REMOVE_FROM_PVP_QUEUE_FACTION_CHANGE = 0x2A3,
        ERR_BATTLEGROUND_JOIN_FAILED = 0x2A4,
        ERR_BATTLEGROUND_JOIN_TIMED_OUT = 0x2A5,
        ERR_MAIL_LIMITED_DURATION_ITEM = 0x2A6,
        ERR_YELL_RESTRICTED = 0x2A7,
        ERR_LFG_ROLE_CHECK_FAILED = 0x2A8,
        ERR_LFG_ROLE_CHECK_FAILED_TIMEOUT = 0x2A9,
        ERR_LFG_ROLE_CHECK_FAILED_NOT_VIABLE = 0x2AA,
        ERR_LFG_GROUP_FULL = 0x2AB,
        ERR_LFG_NO_LFG_OBJECT = 0x2AC,
        ERR_LFG_NO_SLOTS_PLAYER = 0x2AD,
        ERR_LFG_NO_SLOTS_PARTY = 0x2AE,
        ERR_LFG_MISMATCHED_SLOTS = 0x2AF,
        ERR_LFG_PARTY_PLAYERS_FROM_DIFFERENT_REALMS = 0x2B0,
        ERR_LFG_MEMBERS_NOT_PRESENT = 0x2B1,
        ERR_LFG_GET_INFO_TIMEOUT = 0x2B2,
        ERR_LFG_INVALID_SLOT = 0x2B3,
        ERR_LFG_DESERTER_PLAYER = 0x2B4,
        ERR_LFG_DESERTER_PARTY = 0x2B5,
        ERR_LFG_RANDOM_COOLDOWN_PLAYER = 0x2B6,
        ERR_LFG_RANDOM_COOLDOWN_PARTY = 0x2B7,
        ERR_LFG_TOO_MANY_MEMBERS = 0x2B8,
        ERR_LFG_PROPOSAL_FAILED = 0x2B9,
        ERR_LFG_PROPOSAL_DECLINED_SELF = 0x2BA,
        ERR_LFG_PROPOSAL_DECLINED_PARTY = 0x2BB,
        ERR_LFG_NO_SLOTS_SELECTED = 0x2BC,
        ERR_LFG_NO_ROLES_SELECTED = 0x2BD,
        ERR_LFG_ROLE_CHECK_INITIATED = 0x2BE,
        ERR_LFG_PLAYER_DECLINED_ROLE_CHECK = 0x2BF,
        ERR_LFG_JOINED_QUEUE = 0x2C0,
        ERR_LFG_JOINED_LIST = 0x2C1,
        ERR_LFG_LEFT_QUEUE = 0x2C2,
        ERR_LFG_LEFT_LIST = 0x2C3,
        ERR_LFG_ROLE_CHECK_ABORTED = 0x2C4,
        ERR_LFG_CANT_USE_BATTLEGROUND = 0x2C5,
        ERR_LFG_CANT_USE_DUNGEONS = 0x2C6,
        ERR_INVALID_TELEPORT_LOCATION = 0x2C7,
        ERR_CURRENCY_FULL = 0x2C8,
        ERR_TOO_FAR_TO_INTERACT = 0x2C9,
        ERR_DIFFICULTY_CHANGE_COOLDOWN_S = 0x2CA,
        ERR_DIFFICULTY_CHANGE_WORLDSTATE = 0x2CB,
        ERR_DIFFICULTY_CHANGE_ENCOUNTER = 0x2CC,
        ERR_DIFFICULTY_CHANGE_COMBAT = 0x2CD,
        ERR_DIFFICULTY_CHANGE_PLAYER_BUSY = 0x2CE,
        ERR_DIFFICULTY_CHANGE_ALREADY_STARTED = 0x2CF,
        ERR_ARENA_TEAM_PARTY_SIZE = 0x2D0,
        ERR_QUEST_FORCE_REMOVED_S = 0x2D1,
        ERR_IN_RANDOM_BG = 0x2D2,
        ERR_IN_NON_RANDOM_BG = 0x2D3,
        ERR_AUCTION_ENOUGH_ITEMS = 0x2D4,
        ERR_BN_FRIEND_SELF = 0x2D5,
        ERR_BN_FRIEND_ALREADY = 0x2D6,
        ERR_BN_FRIEND_BLOCKED = 0x2D7,
        ERR_BN_FRIEND_REQUEST_SENT = 0x2D8,
        ERR_BN_BROADCAST_THROTTLE = 0x2D9,
        ERR_MAX_VALUE = 0x2DA,
    }

    #endregion

    #region World related

    [Flags]
    public enum CGWorldFrameHitFlags : uint
    {
        HitTestBoundingModels = 1,
        HitTestGround = 0x100,
        HitTestGroundAndStructures = 0x121,
        HitTestLiquid = 0x10000,
        HitTestLiquid2 = 0x20000,
        HitTestLOS = 0x100121,
        HitTestMovableObjects = 0x100000,
        HitTestNothing = 0,
        HitTestSpellLoS = 0x10,
        HitTestUnknown = 0x40,
        HitTestUnknown2 = 0x80,
        HitTestUnknown3 = 0x200000,
        HitTestUnknown4 = 0x400000,
        HitTestWMO = 0x20
    }

    public enum MapType
    {
        World = 0,
        Instance = 1,
        RaidInstance = 2,
        Battleground = 3,
        Arena = 4
    }

    public enum ClickToMoveType
    {
        LeftClick = 0x1,
        Face = 0x2,
        Stop_ThrowsException = 0x3, // Throws a Lua error whenever used. Caused by event state mismatch!
        Move = 0x4,
        NpcInteract = 0x5,
        Loot = 0x6,
        ObjInteract = 0x7,
        Skin = 0x9,
        AttackPosition = 0xA,
        AttackGuid = 0xB,

        ConstantFace = 0xC,

        // This is actually unknown. Usually referenced with Face though.
        FaceOther = 0x8,

        None = 0xD
    }

    public enum TracelineResult
    {
        Collided,
        NoCollision
    }

    public enum InstanceType
    {
        None = 0, // none
        Dungeon = 1, // party
        Raid = 2, // raid
        Battleground = 3, // pvp
        Arena = 4, // arena
        Scenario = 5 // scenario
    }

    public enum MapFlags
    {
        DevMap = 0x2,
        CanToggleDifficulty = 0x100,
        // 0x4000 this is only used for Throne of The Tides map atm
        IsFlexLocking = 0x8000,
        PhaseMap = 0x20000, // some phased maps have this
        PaidRaceChangeDisabled = 0x40000, // used for goblin, worgen and panda starting areas
        // 0x80000 used for map "Ancient Zul'Gurub" only
        // 0x200000 Firelands/Molten Front
        // 0x400000 The Ring of Valor arena
        // 0x800000 mostly pandaria maps flagged with this
        // 0x1000000 continents (except Pandaria)
    }

    #endregion

    #region Unit related

    [Flags]
    public enum UnitFlags : uint
    {
        None = 0,
        Sitting = 0x1,
        Influenced = 0x4,
        PlayerControlled = 0x8,
        Totem = 0x10,
        Preparation = 0x20,
        PlusMob = 0x40,
        NotAttackable = 0x100,
        Looting = 0x400,
        PetInCombat = 0x800,
        PvPFlagged = 0x1000,
        Silenced = 0x2000,
        Pacified = 0x20000,
        Stunned = 0x40000,
        CanPerformAction_Mask1 = 0x60000,
        Combat = 0x80000,
        TaxiFlight = 0x100000,
        Disarmed = 0x200000,
        Confused = 0x400000,
        Fleeing = 0x800000,
        Possessed = 0x1000000,
        NotSelectable = 0x2000000,
        Skinnable = 0x4000000,
        Mounted = 0x8000000,
        Dazed = 0x20000000,
        Sheathe = 0x40000000,
    }

    [Flags]
    public enum UnitFlags2
    {
        FeignDeath = 0x1,
        NoModel = 0x2,
        Flag_0x4 = 0x4,
        Flag_0x8 = 0x8,
        Flag_0x10 = 0x10,
        Flag_0x20 = 0x20,
        ForceAutoRunForward = 0x40,

        /// <summary>
        /// Treat as disarmed?
        /// Treat main and off hand weapons as not being equipped?
        /// </summary>
        Flag_0x80 = 0x80,

        /// <summary>
        /// Skip checks on ranged weapon?
        /// Treat it as not being equipped?
        /// </summary>
        Flag_0x400 = 0x400,

        Flag_0x800 = 0x800,
        Flag_0x1000 = 0x1000,
    }

    [Flags]
    public enum UnitDynamicFlags
    {
        None = 0,
        Lootable = 0x1,
        TrackUnit = 0x2,
        TaggedByOther = 0x4,
        TaggedByMe = 0x8,
        SpecialInfo = 0x10,
        Dead = 0x20,
        ReferAFriendLinked = 0x40,
        IsTappedByAllThreatList = 0x80,
    }

    public enum UnitNPCFlags
    {
        UNIT_NPC_FLAG_NONE = 0x00000000,
        UNIT_NPC_FLAG_GOSSIP = 0x00000001, // 100%
        UNIT_NPC_FLAG_QUESTGIVER = 0x00000002, // guessed, probably ok
        UNIT_NPC_FLAG_UNK1 = 0x00000004,
        UNIT_NPC_FLAG_UNK2 = 0x00000008,
        UNIT_NPC_FLAG_TRAINER = 0x00000010, // 100%
        UNIT_NPC_FLAG_TRAINER_CLASS = 0x00000020, // 100%
        UNIT_NPC_FLAG_TRAINER_PROFESSION = 0x00000040, // 100%
        UNIT_NPC_FLAG_VENDOR = 0x00000080, // 100%
        UNIT_NPC_FLAG_VENDOR_AMMO = 0x00000100, // 100%, general goods vendor
        UNIT_NPC_FLAG_VENDOR_FOOD = 0x00000200, // 100%
        UNIT_NPC_FLAG_VENDOR_POISON = 0x00000400, // guessed
        UNIT_NPC_FLAG_VENDOR_REAGENT = 0x00000800, // 100%
        UNIT_NPC_FLAG_REPAIR = 0x00001000, // 100%
        UNIT_NPC_FLAG_FLIGHTMASTER = 0x00002000, // 100%
        UNIT_NPC_FLAG_SPIRITHEALER = 0x00004000, // guessed
        UNIT_NPC_FLAG_SPIRITGUIDE = 0x00008000, // guessed
        UNIT_NPC_FLAG_INNKEEPER = 0x00010000, // 100%
        UNIT_NPC_FLAG_BANKER = 0x00020000, // 100%
        UNIT_NPC_FLAG_PETITIONER = 0x00040000, // 100% 0xC0000 = guild petitions, 0x40000 = arena team petitions
        UNIT_NPC_FLAG_TABARDDESIGNER = 0x00080000, // 100%
        UNIT_NPC_FLAG_BATTLEMASTER = 0x00100000, // 100%
        UNIT_NPC_FLAG_AUCTIONEER = 0x00200000, // 100%
        UNIT_NPC_FLAG_STABLEMASTER = 0x00400000, // 100%
        UNIT_NPC_FLAG_GUILD_BANKER = 0x00800000, // cause client to send 997 opcode
        UNIT_NPC_FLAG_SPELLCLICK = 0x01000000, // cause client to send 1015 opcode (spell click)
        UNIT_NPC_FLAG_GUARD = 0x10000000, // custom flag for guards
    }

    public enum UnitReaction
    {
        Hated,
        Hostile,
        Unfriendly,
        Neutral,
        Friendly,
        Honored,
        Revered,
        Exalted
    }

    public enum WoWClass
    {
        None = 0,
        Warrior = 1,
        Paladin,
        Hunter,
        Rogue,
        Priest,
        DeathKnight,
        Shaman,
        Mage,
        Warlock,
        Monk,
        Druid
    }

    public enum WoWRace
    {
        Human = 1,
        Orc,
        Dwarf,
        NightElf,
        Undead,
        Tauren,
        Gnome,
        Troll,
        Goblin,
        BloodElf,
        Draenei,
        FelOrc,
        Naga,
        Broken,
        Skeleton,
        Vrykul,
        Tuskarr,
        ForestTroll,
        Taunka,
        NorthrendSkeleton,
        IceTroll,
        Worgen,
        Gilnean,
        Pandaren = 26,
    }

    public enum WoWGender
    {
        Male,
        Female,
        Unknown
    }

    public enum UnitClassificationType
    {
        NotSpecified,
        Normal = 0,
        Elite,
        RareElite,
        WorldBoss,
        Rare,
        Trivial
    }

    public enum CreatureType
    {
        Unknown = 0,
        Beast,
        Dragon,
        Demon,
        Elemental,
        Giant,
        Undead,
        Humanoid,
        Critter,
        Mechanical,
        NotSpecified,
        Totem,
        NonCombatPet,
        GasCloud,
    }

    [Flags]
    public enum FactionMask
    {
        Neutral = 0, // non-aggressive creature
        Player = 1, // any player
        Alliance = 2, // player or creature from alliance team
        Horde = 4, // player or creature from horde team
        Monster = 8 // aggressive creature from monster team
    }

    public enum GossipType
    {
        Banker,
        BattleMaster,
        Binder,
        Gossip,
        Tabard,
        Taxi,
        Trainer,
        Vendor
    }

    #endregion

    #region Player related

    public enum InstanceDifficulty : int
    {
        Normal10 = 0,
        Normal25 = 1,
        Heroic10 = 2,
        Heroic25 = 3,
    }

    public enum MountType
    {
        Unknown = -1,
        EpicGroundOnly = 225,
        Flying = 229,
        Ground,
        Underwater,
        UnderwaterVashjir,
        TransformFlight = 238,
        AhnQiraj = 241,
        ProfessionMount = 247,

        /// <summary> This is both flying and ground mounts, headless horseman has this type. </summary>
        Scaling
    }

    public enum ShapeshiftForm
    {
        Normal = 0,
        Cat = 1,
        TreeOfLife = 2,
        Travel = 3,
        Aqua = 4,
        Bear = 5,
        Ambient = 6,
        Ghoul = 7,
        DireBear = 8,
        CreatureBear = 14,
        CreatureCat = 15,
        GhostWolf = 16,
        BattleStance = 17,
        DefensiveStance = 18,
        BerserkerStance = 19,
        EpicFlightForm = 27,
        Shadow = 28,
        Stealth = 30,
        Moonkin = 31,
        SpiritOfRedemption = 32
    }

    public enum MultiCastSlot
    {
        ElementsFire = 133,
        ElementsEarth,
        ElementsWater,
        ElementsAir,

        AncestorsFire,
        AncestorsEarth,
        AncestorsWater,
        AncestorsAir,

        SpiritsFire,
        SpiritsEarth,
        SpiritsWater,
        SpiritsAir
    }

    public enum Totem
    {
        // Earth Totems
        EarthElemental = 2062,
        Earthbind = 2484,
        Stoneclaw = 5730,
        Stoneskin = 8071,
        StrengthOfEarth = 8075,
        Tremor = 8143,

        // Fire Totems
        FireElemental = 2894,
        Searing = 3599,
        Magma = 8190,
        Flametongue = 8227,

        // Water Totems
        HealingStream = 5394,
        ManaSpring = 5675,
        ManaTide = 16190,
        TranquilMind = 87718,

        // Air Totems
        WrathOfAir = 3738,
        Grounding = 8177,
        ElementalResistance = 8184,
        Windfury = 8512,
    }

    public enum WeaponEnchantments : uint
    {
        // Shaman
        Flametongue = 5,
    }

    public enum RuneType : uint
    {
        Blood,
        Unholy,
        Frost,
        Death
    }

    public enum RuneSlot
    {
        Blood1 = 0,
        Blood2,
        Unholy2,
        Unholy1,
        Frost1,
        Frost2,
    }

    public enum WoWCurrencyType
    {
        /// <summary>
        /// Champion's Seals are the currency rewarded and used at the Argent Tournament.
        /// They are accumulated by completing Argent Tournament daily quests, and can be exchanged with your faction's quartermasters for various rewards.
        /// </summary>
        ChampionSeal = 241,

        /// <summary>
        /// Chef's Awards are currency related to the Cooking skill. They can be earned by completing daily cooking quests in your faction's home city (Stormwind City / Orgrimmar).
        /// They can be used to purchase new cooking recipes from the Sous Chef in your home city.
        /// </summary>
        ChefsAward = 402,

        /// <summary>
        /// Conquest Points are the higher tier of PvP content rewards. They are earned from doing ranked arena matches and rated battlegrounds.
        /// The lower tier currency, Honor Points, is earned from un-rated battlegrounds, un-ranked arena matches, honorable kills, and controlling Wintergrasp.
        /// </summary>
        ConquestPoints = 390,

        /// <summary>
        /// Dalaran Cooking Awards are rewarded from level 80 daily cooking quests in Dalaran.
        /// They can be used to purchase level 400-450 cooking recipes, as well as Northern Spices and the mighty Chef's Hat.
        /// </summary>
        DalaranCookingAward = 81,

        /// <summary>
        /// Dalaran Jewelcrafter's Tokens are rewarded from level 80 jewelcrafting daily quests in Dalaran.
        /// They can be used to purchase level 370-450 jewelcrafting designs.
        /// </summary>
        DalaranJewelcraftersToken = 61,

        /// <summary>
        /// Draenei Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Draenei fragments are all found in Outland.
        /// </summary>
        DraeneiArchaeologyFragment = 398,

        /// <summary>
        /// Dwarf Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Dwarf fragments are found in centers of historical dwarven habitation, such as the Badlands, the Wetlands, and Loch Modan.
        /// </summary>
        DwarfArchaeologyFragment = 384,

        /// <summary>
        /// Fossil Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Fossil fragments are usually found in locations such as Un'Goro Crater and Desolace.
        /// </summary>
        FossilArchaeologyFragment = 393,

        /// <summary>
        /// Honor Points are the lower tier of PvP content rewards. They have replaced all forms of pre 4.0 PvP rewards.
        /// You can earn Honor Points from non-rated battlegrounds, unranked arenas, honorable kills, or from controlling Wintergrasp.
        /// Rated battlegrounds and ranked arenas reward Conquest Points instead.
        /// </summary>
        HonorPoints = 392,

        /// <summary>
        /// Illustrious Jewelcrafter's Tokens are rewarded from faction-based daily quests in your factions home city (Stormwind City / Orgrimmar)
        /// They can be used to purchase level 465-525 jewelcrafting designs from your faction's quartermaster.
        /// </summary>
        IllustriousJewelcrafterToken = 361,

        /// <summary>
        /// Justice Points are a type of currency that is rewarded via participating in instanced PvE content, such as dungeons and raids, and is used to purchase tier sets.
        /// Justice Points are the lower of the two tiers of PvE rewards, and are rewarded for completing your first random normal dungeon each day, as well as for defeating heroic bosses. Raid bosses, as well as the your first random heroic each day, reward Valor Points.
        /// </summary>
        JusticePoints = 395,

        /// <summary>
        /// Mark of the World Tree is the currency that will be used to unlock the The Regrowth and Molten Front Daily Quest Hubs at the player's discretion.
        /// The currency will be rewarded in small amounts from the daily quests in the zone (similar to Champion's Seals) and will be spendable by the player in some manner in order to unlock more dailies and/or cause further storyline progression to occur.
        /// This way players can experience the story and phasing at their own pace, rather than on a timeline or the pace of the rest of the sever.
        /// </summary>
        MarkoftheWorldTree = 416,

        /// <summary>
        /// Nerubian Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Nerubian fragments are all found in Northrend, typically in areas of Nerubian habitation such as Dragonblight.
        /// </summary>
        NerubianArchaeologyFragment = 400,

        /// <summary>
        /// Night Elf Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Night elf fragments are typically found in areas such as Ashenvale and Darkshore.
        /// </summary>
        NightElfArchaeologyFragment = 394,

        /// <summary>
        /// Orc Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Orc fragments are exclusively found in Outland, particularly in areas such as Nagrand. If this confuses you, remember that orcs are native to Outland—they invaded Azeroth through the dark portal in the First War, detailed in the original Warcraft: Orcs and Humans.
        /// </summary>
        OrcArchaeologyFragment = 397,

        /// <summary>
        /// Tol Barad Commendations are the currency rewarded for completing daily quests in Tol Barad. These quests are unlocked when your faction controls the zone.
        /// Tol Barad Commendations can be used to purchase rewards from your faction's Tol Barad Quartermaster.
        /// </summary>
        TolBaradCommendation = 391,

        /// <summary>
        /// Tol'vir Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Tol'vir fragments are exclusively found in level 80+ zones in Azeroth, particularly in areas such as Uldum.
        /// </summary>
        TolvirArchaeologyFragment = 401,

        /// <summary>
        /// Troll Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Troll fragments are frequently found in areas such as The Hinterlands and Stranglethorn Vale.
        /// </summary>
        TrollArchaeologyFragment = 385,

        /// <summary>
        /// Valor Points are a type of currency that is rewarded via participating in instanced PvE content, such as dungeons and raids, and is used to purchase tier sets.
        /// Valor Points are the higher of the two tiers of PvE rewards, 
        /// and are rewarded for completing your first random heroic dungeon each day, as well as for defeating raid bosses. 
        /// Heroic bosses, as well as the your first random normal dungeon each day, reward Justice Points.
        /// </summary>
        ValorPoints = 396,

        /// <summary>
        /// Vrykul Archaeology Fragments are discovered via the Survey ability in Archaeology. They are gathered via surveying, saved up, and used to create the items listed below.
        /// Vrykul fragments are exclusively found in Northrend, especially in areas such as Howling Fjord and Icecrown.
        /// </summary>
        VrykulArchaeologyFragment = 399
    }

    #endregion

    #region Object related

    [Flags]
    public enum WoWObjectType
    {
        Object = 0x1,
        Item = 0x2,
        Container = 0x4,
        Unit = 0x8,
        Player = 0x10,
        GameObject = 0x20,
        DynamicObject = 0x40,
        Corpse = 0x80,
        AreaTrigger = 0x100,
        SceneObject = 0x200,
    }

    [Flags]
    public enum GameObjectFlags : ushort
    {
        None = 0x00000000,
        InUse = 0x00000001,
        Locked = 0x00000002,
        InteractionCondition = 0x00000004,
        Transport = 0x00000008,
        Unknown1 = 0x00000010,
        NeverDespawn = 0x00000020,
        Triggered = 0x00000040,
        Unknown2 = 0x00000080,
        Unknown3 = 0x00000100,
        Damaged = 0x00000200,
        Destroyed = 0x00000400
    }

    public enum GameObjectType : byte
    {
        Door,
        Button,
        QuestGiver,
        Chest,
        Binder,
        Generic,
        Trap,
        Chair,
        SpellFocus,
        Text,
        Goober,
        Transport,
        AreaDamage,
        Camera,
        MapObject,
        MapObjectTransport,
        DuelFlag,
        FishingBobber,
        Ritual,
        Mailbox,
        GuardPost = 21,
        SpellCaster,
        MeetingStone,
        FlagStand,
        FishingHole,
        FlagDrop,
        MiniGame,
        CapturePoint = 29,
        AuraGenerator,
        DungeonDifficulty,
        BarberChair,
        DestructibleBuilding,
        GuildBank,
        Trapdoor
    }

    public enum LockKeyType
    {
        LOCK_KEY_NONE = 0,
        LOCK_KEY_ITEM = 1,
        LOCK_KEY_SKILL = 2
    }

    public enum LockType
    {
        LOCKTYPE_PICKLOCK = 1,
        LOCKTYPE_HERBALISM = 2,
        LOCKTYPE_MINING = 3,
        LOCKTYPE_DISARM_TRAP = 4,
        LOCKTYPE_OPEN = 5,
        LOCKTYPE_TREASURE = 6,
        LOCKTYPE_CALCIFIED_ELVEN_GEMS = 7,
        LOCKTYPE_CLOSE = 8,
        LOCKTYPE_ARM_TRAP = 9,
        LOCKTYPE_QUICK_OPEN = 10,
        LOCKTYPE_QUICK_CLOSE = 11,
        LOCKTYPE_OPEN_TINKERING = 12,
        LOCKTYPE_OPEN_KNEELING = 13,
        LOCKTYPE_OPEN_ATTACKING = 14,
        LOCKTYPE_GAHZRIDIAN = 15,
        LOCKTYPE_BLASTING = 16,
        LOCKTYPE_SLOW_OPEN = 17,
        LOCKTYPE_SLOW_CLOSE = 18,
        LOCKTYPE_FISHING = 19,
        LOCKTYPE_INSCRIPTION = 20,
        LOCKTYPE_OPEN_FROM_VEHICLE = 21
    }

    public struct LockEntry
    {
        public uint ID;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public uint[] Index;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public uint[] Skill;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public uint[] Type;
        //[MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        //public uint Action[];
    }

    #endregion

    #region Spell / Aura related

    public enum WoWApplyAuraType
    {
        None,
        BindSight,
        ModPossess,
        PeriodicDamage,
        PeriodicLeech,
        ModConfuse,
        ModCharm,
        ModFear,
        PeriodicHeal,
        ModAttackspeed,
        ModThreat,
        ModTaunt,
        ModStun,
        ModDamageDone,
        ModDamageTaken,
        DamageShield,
        ModStealth,
        ModStealthDetect,
        ModInvisibility,
        ModInvisibilityDetection,
        ObsModHealth,
        ObsModMana,
        ModResistance,
        PeriodicTriggerSpell,
        PeriodicEnergize,
        ModPacify,
        ModRoot,
        ModSilence,
        ReflectSpells,
        ModStat,
        ModSkill,
        ModIncreaseSpeed,
        ModIncreaseMountedSpeed,
        ModDecreaseSpeed,
        ModIncreaseHealth,
        ModIncreaseEnergy,
        ModShapeshift,
        EffectImmunity,
        StateImmunity,
        SchoolImmunity,
        DamageImmunity,
        DispelImmunity,
        ProcTriggerSpell,
        ProcTriggerDamage,
        TrackCreatures,
        TrackResources,
        Aura46,
        ModParryPercent,
        Aura48,
        ModDodgePercent,
        ModCriticalHealingAmount,
        ModBlockPercent,
        ModCritPercent,
        Dummy,
        ModHitChance,
        ModSpellHitChance,
        Transform,
        ModSpellCritChance,
        ModIncreaseSwimSpeed,
        ModDamageDoneCreature,
        ModPacifySilence,
        ModScale,
        PeriodicHealthFunnel,
        PeriodicManaFunnel,
        PeriodicManaLeech,
        ModCastingSpeedNotStack,
        FeignDeath,
        ModDisarm,
        ModStalked,
        SchoolAbsorb,
        ExtraAttacks,
        ModSpellCritChanceSchool,
        ModPowerCostSchoolPct,
        ModPowerCostSchool,
        ReflectSpellsSchool,
        ModLanguage,
        FarSight,
        MechanicImmunity,
        Mounted,
        ModDamagePercentDone,
        ModPercentStat,
        SplitDamagePct,
        WaterBreathing,
        ModBaseResistance,
        ModRegen,
        ModPowerRegen,
        ChannelDeathItem,
        ModDamagePercentTaken,
        ModHealthRegenPercent,
        PeriodicDamagePercent,
        ModResistChance,
        ModDetectRange,
        PreventsFleeing,
        ModUnattackable,
        InterruptRegen,
        Ghost,
        SpellMagnet,
        ManaShield,
        ModSkillTalent,
        ModAttackPower,
        AurasVisible,
        ModResistancePct,
        ModMeleeAttackPowerVersus,
        ModTotalThreat,
        WaterWalk,
        FeatherFall,
        Hover,
        AddFlatModifier,
        AddPctModifier,
        AddTargetTrigger,
        ModPowerRegenPercent,
        AddCasterHitTrigger,
        OverrideClassScripts,
        ModRangedDamageTaken,
        ModRangedDamageTakenPct,
        ModHealing,
        ModRegenDuringCombat,
        ModMechanicResistance,
        ModHealingPct,
        SharePetTracking,
        Untrackable,
        Empathy,
        ModOffhandDamagePct,
        ModTargetResistance,
        ModRangedAttackPower,
        ModMeleeDamageTaken,
        ModMeleeDamageTakenPct,
        RangedAttackPowerAttackerBonus,
        ModPossessPet,
        ModSpeedAlways,
        ModMountedSpeedAlways,
        ModRangedAttackPowerVersus,
        ModIncreaseEnergyPercent,
        ModIncreaseHealthPercent,
        ModManaRegenInterrupt,
        ModHealingDone,
        ModHealingDonePercent,
        ModTotalStatPercentage,
        ModHaste,
        ForceReaction,
        ModRangedHaste,
        ModRangedAmmoHaste,
        ModBaseResistancePct,
        ModResistanceExclusive,
        SafeFall,
        ModPetTalentPoints,
        AllowTamePetType,
        AddCreatureImmunity,
        RetainComboPoints,
        ReducePushback,
        ModShieldBlockvaluePct,
        TrackStealthed,
        ModDetectedRange,
        SplitDamageFlat,
        ModStealthLevel,
        ModWaterBreathing,
        ModReputationGain,
        PetDamageMulti,
        ModShieldBlockvalue,
        NoPVPCredit,
        ModAoeAvoidance,
        ModHealthRegenInCombat,
        PowerBurnMana,
        ModCritDamageBonusMelee,
        Aura164,
        MeleeAttackPowerAttackerBonus,
        ModAttackPowerPct,
        ModRangedAttackPowerPct,
        ModDamageDoneVersus,
        ModCritPercentVersus,
        DetectAmore,
        ModSpeedNotStack,
        ModMountedSpeedNotStack,
        AllowChampionSpells,
        ModSpellDamageOfStatPercent,
        ModSpellHealingOfStatPercent,
        SpiritOfRedemption,
        AoeCharm,
        ModDebuffResistance,
        ModAttackerSpellCritChance,
        ModFlatSpellDamageVersus,
        ModFlatSpellCritDamageVersus,
        ModResistanceOfStatPercent,
        ModCriticalThreat,
        ModAttackerMeleeHitChance,
        ModAttackerRangedHitChance,
        ModAttackerSpellHitChance,
        ModAttackerMeleeCritChance,
        ModAttackerRangedCritChance,
        ModRating,
        ModFactionReputationGain,
        UseNormalMovementSpeed,
        HasteMelee,
        MeleeSlow,
        ModIgnoreAbsorbSchool,
        ModIgnoreAbsorbForSpell,
        ModCooldown,
        ModAttackerSpellAndWeaponCritChance,
        ModAllWeaponSkills,
        ModIncreasesSpellPctToHit,
        ModXpPct,
        Fly,
        CannotBeDodged,
        ModAttackerMeleeCritDamage,
        ModAttackerRangedCritDamage,
        Aura205,
        Aura206,
        ModIncreaseFlightSpeed,
        ModSpeedFlight,
        ModFlightSpeedAlways,
        Aura210,
        ModFlightSpeedNotStack,
        ModRangedAttackPowerOfStatPercent,
        ModRageFromDamageDealt,
        Aura214,
        ArenaPreparation,
        HasteSpells,
        Aura217,
        HasteRanged,
        ModManaRegenFromStat,
        ModRatingFromStat,
        Aura221,
        Aura222,
        Aura223,
        Aura224,
        PrayerOfMending,
        PeriodicDummy,
        PeriodicTriggerSpellWithValue,
        NoImmediateEffect,
        NoImmediateEffect1,
        ModIncreaseMaxHealth,
        ProcTriggerSpellWithValue,
        MechanicDurationMod,
        Aura233,
        MechanicDurationModNotStack,
        ModDispelResist,
        ControlVehicle,
        ModSpellDamageOfAttackPower,
        ModSpellHealingOfAttackPower,
        ModScale2,
        ModExpertise,
        Aura241,
        ModSpellDamageFromHealing,
        Aura243,
        Aura244,
        ModDurationOfMagicEffects,
        ModDurationOfEffectsByDispel,
        Aura247,
        ModCombatResultChance,
        ConvertRune,
        ModIncreaseHealth2,
        ModEnemyDodge,
        Aura252,
        ModBlockCritChance,
        ModDisarmShield,
        ModMechanicDamageTakenPercent,
        NoReagentUse,
        ModTargetResistBySpellClass,
        ModSpellVisual,
        Aura259,
        ScreenEffect,
        Phase,
        Aura262,
        AllowOnlyAbility,
        Aura264,
        Aura265,
        Aura266,
        ModImmuneAuraApplySchool,
        ModAttackPowerOfStatPercent,
        Aura269,
        ModIgnoreTargetResist,
        ModDamageFromCaster,
        Aura272,
        Aura273,
        Aura274,
        ModIgnoreShapeshift,
        Aura276,
        ModMaxAffectedTargets,
        ModDisarmRanged,
        Aura279,
        ModTargetArmorPct,
        ModHonorGain,
        IncreaseBaseHealthPercent,
        ModHealingReceived,
        Aura284,
        ModAttackPowerOfArmor,
        AbilityPeriodicCrit,
        DeflectSpells,
        Aura288,
        Aura289,
        ModAllCritChance,
        Aura291,
        Aura292,
        Aura293,
        Aura294
    }

    public enum SpellEffectType
    {
        None,
        Instakill,
        SchoolDamage,
        Dummy,
        PortalTeleport,
        TeleportUnits,
        ApplyAura,
        EnvironmentalDamage,
        PowerDrain,
        HealthLeech,
        Heal,
        Bind,
        Portal,
        RitualBase,
        RitualSpecialize,
        RitualActivatePortal,
        QuestComplete,
        WeaponDamageNoschool,
        Resurrect,
        AddExtraAttacks,
        Dodge,
        Evade,
        Parry,
        Block,
        CreateItem,
        Weapon,
        Defense,
        PersistentAreaAura,
        Summon,
        Leap,
        Energize,
        WeaponPercentDamage,
        TriggerMissile,
        OpenLock,
        SummonChangeItem,
        ApplyAreaAuraParty,
        LearnSpell,
        SpellDefense,
        Dispel,
        Language,
        DualWield,
        Jump,
        Jump2,
        TeleportUnitsFaceCaster,
        SkillStep,
        AddHonor,
        Spawn,
        TradeSkill,
        Stealth,
        Detect,
        TransDoor,
        ForceCriticalHit,
        GuaranteeHit,
        EnchantItem,
        EnchantItemTemporary,
        Tamecreature,
        SummonPet,
        LearnPetSpell,
        WeaponDamage,
        CreateRandomItem,
        Proficiency,
        SendEvent,
        PowerBurn,
        Threat,
        TriggerSpell,
        ApplyAreaAuraRaid,
        RestoreItemCharges,
        HealMaxHealth,
        InterruptCast,
        Distract,
        Pull,
        Pickpocket,
        AddFarsight,
        UntrainTalents,
        ApplyGlyph,
        HealMechanical,
        SummonObjectWild,
        ScriptEffect,
        Attack,
        Sanctuary,
        AddComboPoints,
        CreateHouse,
        BindSight,
        Duel,
        Stuck,
        SummonPlayer,
        ActivateObject,
        WmoDamage,
        WmoRepair,
        WmoChange,
        KillCredit,
        ThreatAll,
        EnchantHeldItem,
        BreakPlayerTargeting,
        SelfResurrect,
        Skinning,
        Charge,
        SummonAllTotems,
        KnockBack,
        Disenchant,
        Inebriate,
        FeedPet,
        DismissPet,
        Reputation,
        SummonObjectSlot1,
        SummonObjectSlot2,
        SummonObjectSlot3,
        SummonObjectSlot4,
        DispelMechanic,
        SummonDeadPet,
        DestroyAllTotems,
        DurabilityDamage,
        SpellEffect112,
        ResurrectNew,
        AttackMe,
        DurabilityDamagePct,
        SkinPlayerCorpse,
        SpiritHeal,
        Skill,
        ApplyAreaAuraPet,
        TeleportGraveyard,
        NormalizedWeaponDmg,
        SpellEffect122,
        SendTaxi,
        PlayerPull,
        ModifyThreatPercent,
        StealBeneficialBuff,
        Prospecting,
        ApplyAreaAuraFriend,
        ApplyAreaAuraEnemy,
        RedirectThreat,
        SpellEffect131,
        PlayMusic,
        UnlearnSpecialization,
        KillCredit2,
        CallPet,
        HealPct,
        EnergizePct,
        LeapBack,
        ClearQuest,
        ForceCast,
        SpellEffect141,
        TriggerSpellWithValue,
        ApplyAreaAuraOwner,
        SpellEffect144,
        SpellEffect145,
        ActivateRune,
        QuestFail,
        SpellEffect148,
        SpellEffect149,
        SpellEffect150,
        TriggerSpell2,
        SpellEffect152,
        SpellEffect153,
        TeachTaxiNode,
        TitanGrip,
        EnchantItemPrismatic,
        CreateItem2,
        Milling,
        AllowRenamePet,
        SpellEffect160,
        TalentSpecCount,
        TalentSpecSelect,
        SpellEffect163,
        SpellEffect164,
        TotalSpellEffects
    }

    public enum WoWSpellFocus
    {
        None,
        Anvil,
        Loom,
        Forge,
        CookingFire,
        ShardsofMyzrael,
        WinterhoofWaterWell,
        ThunderhornWaterWell,
        WildmaneWaterWell,
        TribalFire,
        MachineShop,
        ShadowglenMoonwell,
        StarbreezeVillageMoonwell,
        PoolsofArlithrienMoonwell,
        OracleGladeMoonwell,
        VentureCoAirport,
        VentureCoWagonBlue,
        VentureCoWagonRed,
        NGExplosivesRed,
        NGExplosivesBlue,
        FlameofUzel,
        AshenvaleMoonwell,
        SeawornAltar,
        NearbyTubers,
        UndercitySummoningCircle = 43,
        ShamanShrine = 63,
        StormwindSummoningCircle = 83,
        BarrensSummoningCircle = 103,
        MirrorLakeWaterfall = 123,
        TalonDen = 143,
        XavianWaterfall = 163,
        StoneofOuterBinding,
        ManaRiftDisturbance = 183,
        OrgrimmarSummoningCircle = 203,
        WrathscaleFountain = 223,
        QuilboarWateringHole,
        WaterPuritySilverpine,
        SpringWell,
        TempleoftheMoonFountain = 243,
        JinthaAlorAltar = 263,
        PirateShipBilge,
        EquinexMonolith = 283,
        WitherbarkVillage = 303,
        ShadraAlorAltar,
        SandsorrowWatchWaterHole = 323,
        HatetalonStones = 343,
        EcheyakeesLair = 363,
        TheDeadTree = 383,
        MakeshiftHelipad = 403,
        CircleofAquementas = 423,
        SanctumoftheFallenGod,
        theFirstTidePool = 443,
        theSecondTidePool,
        theThirdTidePool,
        theFourthTidePool,
        GorishiHiveHatchery = 463,
        MiblonSnarltooth = 483,
        GadgetzanGraveyard = 503,
        theruinsofIrontreeWoods = 523,
        BlackForge = 543,
        GolakkaCrater = 563,
        TomboftheSeven = 583,
        FlatUnGoroRock = 603,
        PreservedThreshadonCarcass,
        BlackAnvil = 623,
        GorishiSilithidCrystal = 643,
        CorruptedMoonwell,
        AlchemyLab = 663,
        UnforgedSealofAscension = 683,
        AuberdineMoonwell = 703,
        BlackwoodFurbolgNorthBonfire,
        CliffspringRiverWaterfall,
        FirePlumeRidgeHotSpot = 723,
        UroksTributePile = 743,
        AndorhalSiloTemporalRift = 763,
        StoneofShyRotam = 783,
        SacredFireofLife = 803,
        ScarletCrusadeForwardCamp,
        AndorhalTower,
        ScholomanceViewingRoom = 823,
        theJaedenarCorruptMoonWell = 843,
        UmisFriend = 863,
        Moonwell = 883,
        FirePlumeRidgeLavaLake = 903,
        thecrateinthecenteroftheNorthridgeLumberMill = 923,
        MoonkinStone = 943,
        DarrowshireTownSquare,
        BrightLightBeam = 963,
        MarkofDetonation = 983,
        CliffspringFallsCaveMouth = 1003,
        DreadmistPeakPool,
        TheDeadGoliaths = 1023,
        ShrineofRemulos = 1043,
        FoulwealdTotemMound = 1063,
        DirePool = 1083,
        MaraudonPortal = 1103,
        HordeGlobeofScrying = 1123,
        EasternCrater = 1143,
        WesternCrater,
        SnowfallGraveyard,
        AllianceGlobeofScrying = 1163,
        DunBaldarCourtyard,
        FrostwolfKeepCourtyard,
        SnowfallGraveyard2 = 1183,
        EastCrater,
        WestCrater,
        OrangeCrystalPool = 1203,
        OnyxiasFlameBreath = 1223,
        KroshiusRemains = 1243,
        PedestalofImmolthar = 1263,
        CircleofDarkSummoning,
        TheGreatOssuary = 1283,
        TerrordaleHauntingSpirit,
        AeriePeakTownCenter = 1303,
        UthersTombStatue = 1323,
        GromsMonument,
        PaglesPointe = 1343,
        AltarofZanza,
        Southshore,
        BonesofGrakkarond,
        ForsakenStinkBomb,
        DropOffPoint,
        SwirlingMaelstrom,
        HighChiefWinterfallsCave,
        FireworkLauncher,
        ClusterLauncher,
        GreaterMoonlight,
        VoonesChamber,
        AlzzinsChamber,
        TheCrimsonThrone,
        RasFrostwhispersChamber,
        TheBeastsChamber,
        HauntedLocus,
        BlackrockDepthsArena,
        PHCrystalCorpse,
        IcebellowAnvil,
        EversongRunestone,
        ConsecratedEarth,
        MidsummerBonfire,
        Maypole,
        AltarofAggonar,
        BonesofAggonar,
        SchoolofRedSnapper,
        KrunSpinebreakersCorpse,
        ThalanaarMoonwell,
        ConcealedControlPanel,
        AltarofNaias,
        DiscreetLocation,
        RuneofSummoning,
        FelBrazier,
        youtobeinTraitorsCovewhiletheNagaFlagisup,
        SedaisCorpse,
        NazzivusMonument,
        ImpactSiteCrystal,
        AlteredBloodmystCrystal,
        AxxarienCrystal,
        thesouthernendoftheMastersTerrace,
        MedivhsTelescope,
        AlonsusChapelEternalFlame,
        BloodmystWaterfall,
        SteamPumpControls,
        WindyreedHut,
        EarthenBrand,
        UndergroundWaterSource,
        BohamuRuinsStairs,
        DaggerfenRock,
        BurningBladepyreintheBurningBladeRuins,
        YsielsBalcony,
        BlazingWarmaulPyre,
        VeilShalasTotem,
        TrampledSkeleton,
        AllianceCannon,
        HordeBladeThrower,
        LegionAntenna,
        ScorchedGroveRunestone,
        Bookcase,
        WeaponRack,
        Dresser,
        Footlocker,
        RuinedAllianceSiegeTower,
        UncontrolledScrapReaverX,
        KirinVarRune,
        ArchmageVargothsOrb,
        ElrendarFalls,
        DragonSkeleton,
        EtherealTeleportPad,
        ArklonBrazier,
        VoidStone,
        ManaforgeBnaarPipe,
        DraeneiBanner,
        EarthbindersCircle,
        SalhadaarsPowerConduit,
        SocretharsTeleporter,
        EcoDomeSutheronGenerator,
        youtobeclosertoManaforgeUltris,
        NorthmaulTower,
        AltarofShadows,
        ShadowmoonTuberMound,
        RokgahBloodgrip,
        ManaLoom,
        AncientDraeneiAltar,
        OgreBuildingEntrance,
        BladesEdgeArakkoaCircle,
        LashhanSpellCircle,
        VekhnirCircleofPower,
        youtobeattheendofthebridge,
        TorgossBane,
        VekhnirSpellCircle,
        youtobestandingnexttoGuldanattheAltarofDamnation,
        LegionHoldTeleporter,
        RuuanokOracleCircle,
        LegionCommunicationDevice,
        ForemanRazelcraz,
        PortalatMarshlightLake,
        BladesEdgeQuestBirdSpying,
        MalukazsCandles,
        BleedingHollowForge,
        MarmotDen,
        GehennaTeleporter,
        ForceCommanderGoraxsCorpse,
        ZethGorTower,
        UnguardedSummoningSite,
        LockedWyvernCage,
        GorgromsCorpse,
        DeathsDoorFelCannon,
        WrithingMoundSummoningCircle,
        AltarofGocandthatGochasnotbeensummoned,
        TheRavensClaw,
        ArakkoaShrine,
        SoulgrindersAltar,
        ShartuulsTransporterPlatform,
        ShipwreckDebris,
        BlackhoofVillageWindmill,
        GrimtotemTent,
        HyalFamilyMonument,
        BurningTrollHut,
        EntrancetoOnyxiasLair,
        SwamplightManorDock,
        TheWyrmcallersPlatform,
        ShatteredStrandCannon,
        cannononnorthernAlliancewall,
        TheThanesPyre,
        FrozenWaterfall,
        proximitytoplaguehoundcagesatVengeanceLanding,
        StandingattheBoothCounter,
        CauldronofVrykulBlood,
        HarrissPlagueSamples,
        youtobeclosertoplaguehoundcages,
        BrokenTablet,
        SunkenBoat,
        CenterofBaleheim,
        BrewfestMugRequest,
        WaltsTransportRune,
        IronDwarfTransportRune,
        LeyLinesofQuelDanas,
        RazorthornDirtMound,
        CrystalWard,
        LegionTeleporter,
        HauthaasAnvil,
        VrykulBurialMound,
        WestriftSeismicAnomaly,
        JSBReusepost,
        NerubarSinkhole,
        SnarlfangsTotem,
        EnkilahCauldron,
        youtobeatornearthefrontofaKvaldirship,
        youtobestandingattheendofWarsongJetty,
        ImprisonedBerylSorcerer,
        BerylForceShield,
        DenofDyingPlagueCauldron,
        SouthSinkhole,
        youtobeatthecrossroadseastofWarsongHoldwithanAllianceDeserterintow,
        youtobestandingnexttoBloodmageLaurithattheBloodsporePlains,
        ShatteredSunPortal,
        ShatteredSunPortal2,
        CrashedFlyingMachine,
        GeyserFieldsSteamVent,
        NexusDimensionalRift,
        FarshireGrain,
        SaragosasLanding,
        proximitytoaScourgesinkhole,
        NorthwestNexusEntrance,
        DrakurusBrazier,
        EastEndofThorModanTunnel,
        TuakeasFishingHook,
        ToaluusBrazier,
        FizzcrankPracticeParachuteZone,
        FizzcrankParatrooperTeleporter,
        LeyLineFocusontheBeach,
        LeyLineFocusintheLothalorWoodlands,
        LeyLineFocusUndertheLake,
        DrakiljinGongs,
        MarkedColdwindTree,
        CenterofthepitundertheSurgeNeedle,
        depthsbelowVordrassilsremains,
        depthsbelowVordrassilsLimb,
        depthsbelowVordrassilsTears,
        HanselBauer,
        GromtharsChallengingArea,
        WintergardeGryphonStation,
        NewHearthglenLumbermill,
        VordrassilsSapling,
        Basecamp,
        ObsidianDragonshrineExitPath,
        youtobestandingnexttoSiegeEngineerQuarterflash,
        NecromanticRune,
        youtobestandingatoneoftheentrancepointstoWintergardeMine,
        SchoolofNorthernSalmon,
        youtobestandinginthecenteroftheruinsattheForgottenShore,
        youtobeatthefrontoftheWintergardeMausoleum,
        RuunasCrystalBall,
        SquirePercy,
        thatyoubeclosertoAlystrostheVerdantKeeper,
        FrostmourneAltar,
        thatyoubeonthesandsoftheBronzeDragonshrine,
        VrykulHawkRoost,
        ScourgedMummyFire,
        DrakkariRitualStatue,
        FinklesteinsCauldron,
        MistwhisperWeatherShrine,
        OfferingBowl,
        DrakkariPedestal,
        FallenLog,
        AncientDirtMound,
        NerubianCrater,
        Runeforge,
        LandingPad,
        Scourgewagon,
        QuetzlunsCorpseandthattheProphetofQuetzlunbepresentandunengaged,
        AltarofKartak,
        GreatLightningStone,
        WarlordZolMazpresentandunengagedincombat,
        TopoftheSuntouchedPillar,
        ConvocationSummoningCircle,
        SoakedFertileDirt,
        TopofSholazarPillar,
        TopoftheGlimmeringPillar,
        ExposedLifebloodPillarCrystal,
        UzoDeathcaller,
        ArchbishopLandgrenscorpseandLordCommanderAretenotbepresent,
        SchoolofTastyReefFish,
        MagmawyrmResurrectionChamber,
        FrostgutsAltar,
        GarmTeleporter,
        ThaneUfrangtheMightypresentandseated,
        NorthernIceSpike,
        IcyCrater,
        VanguardInfirmary,
        Snowdrift,
        theBroodmothersNest,
        KLanding,
        ThaneIllskarbepresentandthatheandhischampionsnotbeengagedinbattle,
        PileofCrusaderSkulls,
        MalykrissFurnace,
        AhnkahetBrazier,
        SanctumofReanimationSlab,
        DalaranFountain,
        YmirheimPeakSkulls,
        MordretharPlagueCauldron,
        GrimkorsOrb,
        CultistsCauldron,
        AlumethsSoulstone,
        youtobenearaLexiconofPower,
        SmolderingScrap,
        AltaroftheEbonDepths,
        CorpseoftheFallenWorg,
        UnlitSignalFire = 1596,
        DrakMarOfferingRing,
        TournamentStables = 1599,
        BlackKnightsGryphon = 1601,
        StoneBlock,
        GhostlyCookingFire = 1613,
        MysteriousSnowMound = 1618,
        MistcallersCave = 1620,
        TualiqMonuments,
        thedeckofBorsFury,
        ForgemastersAnvil = 1636,
        CrownSupplyCamp = 1639,
        Sunwell = 1641,
        ChemicalWagon = 1650,
        GatesofStormwind = 1692,
        CultistAltar,
        CultistRitualCircle = 1695
    }

    public enum WoWSpellMechanic
    {
        None,
        Charmed,
        Disoriented,
        Disarmed,
        Distracted,
        Fleeing,
        Gripped,
        Rooted,
        Slowed,
        Silenced,
        Asleep,
        Snared,
        Stunned,
        Frozen,
        Incapacitated,
        Bleeding,
        Healing,
        Polymorphed,
        Banished,
        Shielded,
        Shackled,
        Mounted,
        Infected,
        Turned,
        Horrified,
        Invulnerable,
        Interrupted,
        Dazed,
        Discovery,
        Invulnerable2,
        Sapped,
        Enraged,
        End
    }

    [Flags]
    public enum WoWSpellSchool
    {
        None = 0,
        Physical = 1,
        Holy = 2,
        Fire = 4,
        Nature = 8,
        Frost = 16,
        Shadow = 32,
        Arcane = 64
    }

    public enum KnownSpellType : uint
    {
        Learned = 1,
        NotLearned = 2,
        PetAction = 3,
        FlyOut = 4,
    }

    [Flags]
    public enum AuraFlags
    {
        Active = 0x80,
        Passive = 0x10, // Check if !Active
        Harmful = 0x20
    }

    #endregion

    #region Item related

    [Flags]
    public enum ItemFlags : uint
    {
        None = 0x00000000,
        Unknown1 = 0x00000001,
        Conjured = 0x00000002,
        Openable = 0x00000004,
        Heroic = 0x00000008,
        Deprecated = 0x00000010,
        Indestructible = 0x00000020,
        Consumable = 0x00000040,
        NoEquipCooldown = 0x00000080,
        Unknown2 = 0x00000100,
        Wrapper = 0x00000200,
        Unknown3 = 0x00000400,
        PartyLoot = 0x00000800,
        Refundable = 0x00001000,
        Charter = 0x00002000,
        Unknown4 = 0x00004000,
        Unknown5 = 0x00008000,
        Unknown6 = 0x00010000,
        Unknown7 = 0x00020000,
        Prospectable = 0x00040000,
        UniqueEquip = 0x00080000,
        Unknown8 = 0x00100000,
        UsableInArena = 0x00200000,
        Throwable = 0x00400000,
        UsableWhenShapeshifted = 0x00800000,
        Unknown9 = 0x01000000,
        SmartLoot = 0x02000000,
        UnusableInArena = 0x04000000,
        BindToAccount = 0x08000000,
        TriggeredCast = 0x10000000,
        Millable = 0x20000000,
        Unknown10 = 0x40000000,
        Unknown11 = 0x80000000,
    }

    [Flags]
    public enum ItemFlags2 : uint
    {
        HordeOnly = 0x1,
        AllianceOnly = 0x2,
        NeedRollDisabled = 0x100,
        CasterWeapon = 0x200,
    }

    public enum ItemQuality
    {
        Poor = 0, // gray
        Common, // white
        Uncommon, // green
        Rare, // blue
        Epic, // purple
        Legendary, // orange
        Artifact, // golden yellow
        Heirloom, // light yellow
    }

    public enum ItemClass
    {
        Consumable = 0,
        Container,
        Weapon,
        Gem,
        Armor,
        Reagent,
        Projective,
        TradeGoods,
        Generic,
        Recipe,
        Money,
        Quiver,
        Quest,
        Key,
        Permanent,
        Miscellaneous,
        Glyph
    }

    public enum ItemSubclassConsumable
    {
        Consumable = 0,
        Potion,
        Elixir,
        Flask,
        Scroll,
        FoodDrink,
        ItemEnhancement,
        Bandage,
        Other,
    }

    public enum ItemSubclassContainer
    {
        Bag,
        SoulBag,
        HerbBag,
        EnchantingBag,
        GemBag,
        MiningBag,
        LeatherworkingBag,
        InscriptionBag,
        TackleBox,
    }

    public enum ItemArmorClass
    {
        None = -1,
        Misc,
        Cloth,
        Leather,
        Mail,
        Plate,
        Buckler,
        Shield,
        Libram,
        Idol,
        Totem,
        Sigil
    }

    public enum ItemWeaponClass
    {
        None = -1,
        Axe,
        AxeTwoHand,
        Bow,
        Gun,
        Mace,
        MaceTwoHand,
        Polearm,
        Sword,
        SwordTwoHand,
        Staff = 10,
        Exotic,
        ExoticTwoHand,
        Fist,
        Misc,
        Dagger,
        Thrown,
        Spear,
        Crossbow,
        Wand,
        FishingPole
    }

    public enum ItemBondType
    {
        None,
        OnPickup,
        OnEquip,
        OnUse,
        Quest
    }

    public enum WoWPowerType
    {
        Mana = 0,
        Rage = 1,
        Focus = 2,
        Energy = 3,
        Happiness = 4,
        Runes = 5,
        RunicPower = 6,
        Health = 7,
        Unknown = 8
    }

    public enum EquipSlot
    {
        None = -1,
        Head = 0,
        Neck,
        Shoulders,
        Body,
        Chest,
        Waist,
        Legs,
        Feet,
        Wrists,
        Hands,
        Finger1,
        Finger2,
        Trinket1,
        Trinket2,
        Back,
        MainHand,
        OffHand,
        Ranged,
        Tabard,
        Bag1,
        Bag2,
        Bag3,
        Bag4,

        Start = Head,
        End = Bag4,
    }

    public enum BagSlot
    {
        Bag1,
        Bag2,
        Bag3,
        Bag4,
        Bank1,
        Bank2,
        Bank3,
        Bank4,
        Bank5,
        Bank6,
        Bank7
    }

    public enum InventoryType
    {
        None = 0,
        Head,
        Neck,
        Shoulders,
        Body,
        Chest,
        Waist,
        Legs,
        Feet,
        Wrists,
        Hands,
        Finger,
        Trinket,
        Weapon,
        Shield,
        Ranged,
        Cloak,
        TwoHandedWeapon,
        Bag,
        Tabard,
        Robe,
        WeaponMainHand,
        WeaponOffHand,
        Holdable,
        Ammo,
        Thrown,
        RangedRight,
        Quiver,
        Relic
    }

    public enum Stat
    {
        None,
        MinDamage,
        MaxDamage,
        Speed,
        SpeedBaseLine,
        DPS,
        Armor,
        HolyResistance,
        FireResistance,
        NatureResistance,
        FrostResistance,
        ShadowResistance,
        ArcaneResistance,
        MeleeAttackPower,
        AttackPowerInForms,
        Mana,
        Health,
        Agility,
        Strength,
        Intellect,
        Spirit,
        Stamina,
        DefenseRating,
        DodgeRating,
        ParryRating,
        BlockRating,
        HitRatingMelee,
        HitRatingRanged,
        HitRatingSpell,
        CriticalStrikeRatingMelee,
        CriticalStrikeRatingRanged,
        CriticalStrikeRatingSpell,
        HitAvoidanceRatingMelee,
        HitAvoidanceRatingRanged,
        HitAvoidanceRatingSpell,
        CriticalStrikeAvoidanceRatingMelee,
        CriticalStrikeAvoidanceRatingRanged,
        CriticalStrikeAvoidanceRatingSpell,
        HasteRatingMelee,
        HasteRatingRanged,
        HasteRatingSpell,
        HitRating,
        CriticalStrikeRating,
        HitAvoidanceRating,
        CriticalStrikeAvoidanceRating,
        ResilienceRating,
        HasteRating,
        ExpertiseRating,
        AttackPower,
        RangedAttackPower,
        BonusHealing,
        BonusDamage,
        ManaRegeneration,
        ArmorPenetrationRating,
        SpellPower,
        HealthPer5Sec,
        SpellPenetration,
        BlockValue,
        ManaPer5Sec,
        RagePer5Sec,
        FocusPer5Sec,
        EnergyPer5Sec,
        HappinessPer5Sec,
        RunesPer5Sec,
        RunicPowerPer5Sec,
        MetaSocket,
        RedSocket,
        YellowSocket,
        BlueSocket,
        PrismaticSocket,
        Mastery
    }

    public enum ItemStatType
    {
        None = -1,
        Health = 1,
        Mana,
        Agility,
        Strength,
        Intellect,
        Spirit,
        Stamina,
        DefenseRating = 12,
        DodgeRating,
        ParryRating,
        ShieldBlockRating,
        MeleeHitRating,
        RangedHitRating,
        SpellHitRating,
        MeleeCriticalStrikeRating,
        RangedCriticalStrikeRating,
        SpellCriticalStrikeRating,
        MeleeHitAvoidanceRating,
        RangedHitAvoidanceRating,
        SpellHitAvoidanceRating,
        MeleeCriticalAvoidanceRating,
        RangedCriticalAvoidanceRating,
        SpellCriticalAvoidanceRating,
        MeleeHasteRating,
        RangedHasteRating,
        SpellHasteRating,
        HitRating,
        CriticalStrikeRating,
        HitAvoidanceRating,
        CriticalAvoidanceRating,
        ResilienceRating,
        HasteRating,
        ExpertiseRating,
        AttackPower,
        RangedPower,
        FeralAttackPower,
        DamageDone,
        HealingDone,
        ManaEvery5Seconds,
        ArmorPenetration,
        SpellPower,
        HealthEvery5Seconds,
        SpellPenetration,
        BlockValue,
        MasteryRating = 49,

        Armor = 1000,
        DPS = 1001,
    }

    public enum StatTypes
    {
        Armor,
        HolyResistance,
        FireResistance,
        NatureResistance,
        FrostResistance,
        ShadowResistance,
        ArcaneResistance,
        AttackPower2,
        MeleeAttackPower,
        RangedAttackPower2,
        AttackPowerInForms,
        Mana,
        Health,
        Agility = 14,
        Strength,
        Intellect,
        Spirit,
        Stamina,
        DefenseRating = 23,
        DodgeRating,
        ParryRating,
        BlockRating,
        HitRatingMelee,
        HitRatingRanged,
        HitRatingSpell,
        CriticalStrikeRatingMelee,
        CriticalStrikeRatingRanged,
        CriticalStrikeRatingSpell,
        HitAvoidanceRatingMelee,
        HitAvoidanceRatingRanged,
        HitAvoidanceRatingSpell,
        CriticalStrikeAvoidanceRatingMelee,
        CriticalStrikeAvoidanceRatingRanged,
        CriticalStrikeAvoidanceRatingSpell,
        HasteRatingMelee,
        HasteRatingRanged,
        HasteRatingSpell,
        HitRating,
        CriticalStrikeRating,
        HitAvoidanceRating,
        CriticalStrikeAvoidanceRating,
        ResilienceRating,
        HasteRating,
        ExpertiseRating,
        AttackPower,
        RangedAttackPower,
        BonusHealing = 52,
        BonusDamage,
        ManaRegeneration,
        ArmorPenetrationRating,
        SpellPower,
        HealthPer5Sec,
        SpellPenetration,
        BlockValue,
        Mastery,
        ArmorBonus,
        FireResistance2,
        FrostResistance2,
        HolyResistance2,
        ShadowResistance2,
        NatureResistance2,
        ArcaneResistance2,
        BlockValue2,
        ManaPer5Sec,
        RagePer5Sec,
        FocusPer5Sec,
        HappinessPer5Sec,
        RunesPer5Sec,
        RunicPowerPer5Sec,
        ITEM_MOD_POWER_REGEN6_SHORT,
        ITEM_MOD_POWER_REGEN7_SHORT,
        ITEM_MOD_POWER_REGEN8_SHORT,
        ITEM_MOD_POWER_REGEN9_SHORT,
        ITEM_MOD_POWER_REGEN10_SHORT,
        HealthPer5Sec2,
        MetaSocket,
        RedSocket,
        YellowSocket,
        BlueSocket,
        HydraulicSocket,
        CogWheelSocket,
        PrismaticSocket,
        PrismaticSocket2
    }

    public enum AuraType
    {
        OBS_MOD_HEALTH = 20,
        OBS_MOD_MANA = 21,
        MOD_REGEN = 84,
        MOD_POWER_REGEN = 85,
    }

    public enum ItemGemClass
    {
        None = -1,
        Red,
        Blue,
        Yellow,
        Purple,
        Green,
        Orange,
        Meta,
        Simple,
        Prismatic
    }

    [Flags]
    public enum SocketColor : uint
    {
        None = 0,
        Meta = 1,
        Red = 2,
        Yellow = 4,
        Blue = 8
    }

    #endregion

    #region Quest related

    public enum QuestGiverStatus
    {
        None,
        Unavailable,
        LowLevelAvailable,
        LowLevelTurnInRepeatable,
        LowLevelAvailableRepeatable,
        Incomplete,
        TurnInRepeatable,
        AvailableRepeatable,
        Available,
        TurnInInvisible,
        TurnIn
    }

    public enum QuestType : uint
    {
        Group = 1u,
        Life = 21u,
        PvP = 41u,
        Raid = 62u,
        Dungeon = 81u,
        WorldEvent,
        Legendary,
        Escort,
        Heroic,
        Raid_10 = 88u,
        Raid_25
    }

    #endregion
}